var englishOneLineDB_Std10 = [

// ---------------- Chapter 1: Against the Odds (Std 10 English) ----------------
    { chapter: 1, marks: 1, q: "Where is Taj Nagar village located?", ans: "Near Gurgaon" },
    { chapter: 1, marks: 1, q: "What was the main demand of the people of Taj Nagar?", ans: "A railway station" },
    { chapter: 1, marks: 1, q: "How much money did the people collect to build the railway station?", ans: "21 lakh rupees" },
    { chapter: 1, marks: 1, q: "What is the occupation of most of the people in Taj Nagar?", ans: "Farming (Farmers)" },
    { chapter: 1, marks: 1, q: "What reason did the railway department give for refusing to build the station?", ans: "Lack of funds" },
    { chapter: 1, marks: 1, q: "When did the villagers of Taj Nagar start their demand for a railway station?", ans: "Twenty-five years ago (in 1982)" },
    { chapter: 1, marks: 1, q: "What was the approximate population of Taj Nagar village?", ans: "Three thousand" },
    { chapter: 1, marks: 1, q: "What committee did the villagers form to build the station?", ans: "An 11-member committee" },
    { chapter: 1, marks: 1, q: "When did the Taj Nagar railway station become operational?", ans: "January 7, 2010" },
    { chapter: 1, marks: 1, q: "In which state is Sitapur district located?", ans: "Uttar Pradesh" },
    { chapter: 1, marks: 1, q: "More than what percentage of households in Sitapur were without electricity?", ans: "More than 60%" },
    { chapter: 1, marks: 1, q: "Which organization was working to provide electricity in Sitapur?", ans: "MGP (Mera Gao Power)" },
    { chapter: 1, marks: 1, q: "How many customers did MGP connect to solar power?", ans: "More than 3500" },
    { chapter: 1, marks: 1, q: "For how many rupees a week did the customers get two LEDs and a charging point?", ans: "25 rupees" },
    { chapter: 1, marks: 1, q: "How is the cost of solar power compared to kerosene?", ans: "Cheaper (Half the cost)" },
    { chapter: 1, marks: 1, q: "Who became the first electrician of the village?", ans: "Azaz" },
    { chapter: 1, marks: 1, q: "In which direction is the solar panel set up?", ans: "Towards the South (to capture sunlight)" },
    { chapter: 1, marks: 1, q: "What kind of roof is chosen to install a solar panel?", ans: "A strong, brick-walled roof without windows" },
    { chapter: 1, marks: 1, q: "How does the arrival of solar light benefit the weavers at night?", ans: "It makes it easier for them to work" },
    { chapter: 1, marks: 1, q: "Where is the Palakkad Public Library located?", ans: "In Kerala" },
    { chapter: 1, marks: 1, q: "When was the Palakkad Library established?", ans: "In September 2013" },
    { chapter: 1, marks: 1, q: "Out of the 1000 members of the library, how many are women?", ans: "One-third (around 300)" },
    { chapter: 1, marks: 1, q: "What special arrangement was made for women in the library?", ans: "A separate reading room" },
    { chapter: 1, marks: 1, q: "When was the women's unit started?", ans: "In February 2014" },
    { chapter: 1, marks: 1, q: "On what subjects are workshops held in the library?", ans: "Home economics, gardening, and child care" },
    { chapter: 1, marks: 1, q: "What do women learn in the library?", ans: "Solving family disputes and legal advice" },
    { chapter: 1, marks: 1, q: "For whom has the Palakkad Library become a beacon?", ans: "For women empowerment" },
    { chapter: 1, marks: 1, q: "To which cities did the people of Taj Nagar previously go for work?", ans: "Gurgaon, Delhi, and Rewari" },
    { chapter: 1, marks: 1, q: "How did setting up a microgrid in Sitapur benefit the environment?", ans: "It reduced pollution" },
    { chapter: 1, marks: 1, q: "Taj Nagar station is the first station in India where...", ans: "Not a single rupee of the railway was spent" },

// ---------------- Chapter 2: The Human Robot (Std 10 English) ----------------
    { chapter: 2, marks: 1, q: "What is the name of the robot in the lesson 'The Human Robot'?", ans: "Ram Singh-070" },
    { chapter: 2, marks: 1, q: "Who bought the Ram Singh robot?", ans: "Prem Chopra" },
    { chapter: 2, marks: 1, q: "What were the colors of the robots in Super Robots Plaza?", ans: "Metallic blue, green, and silver" },
    { chapter: 2, marks: 1, q: "Which robot did the salesman show to Prem Chopra?", ans: "The metallic blue one" },
    { chapter: 2, marks: 1, q: "What was the general work of the Ram Singh-070 robot?", ans: "Household chores, cleaning, shopping, etc." },
    { chapter: 2, marks: 1, q: "How many principles were in-built in the robot's system?", ans: "Three (3)" },
    { chapter: 2, marks: 1, q: "What was the first principle of the robot?", ans: "The robot will obey its master" },
    { chapter: 2, marks: 1, q: "What was the second principle of the robot?", ans: "The robot will not harm humans" },
    { chapter: 2, marks: 1, q: "What was the third principle of the robot?", ans: "The robot will not let harm come to itself" },
    { chapter: 2, marks: 1, q: "Why did Prem Chopra misuse the robot?", ans: "For stealing" },
    { chapter: 2, marks: 1, q: "How was the command to steal given to the robot?", ans: "Through a remote control" },
    { chapter: 2, marks: 1, q: "From which shop did Prem Chopra make the robot steal?", ans: "Jhaveri Bros" },
    { chapter: 2, marks: 1, q: "What do the police use to catch the thief?", ans: "Computerized cameras" },
    { chapter: 2, marks: 1, q: "What was the robot stealing when it was caught?", ans: "Precious gems" },
    { chapter: 2, marks: 1, q: "From where was Prem Chopra arrested?", ans: "From his home" },
    { chapter: 2, marks: 1, q: "From where was Prem Chopra released on bail?", ans: "From the police station" },
    { chapter: 2, marks: 1, q: "Who was Prem Chopra's lawyer?", ans: "Counsel Goel" },
    { chapter: 2, marks: 1, q: "For how long does the robot's memory tape store information?", ans: "The previous one week" },
    { chapter: 2, marks: 1, q: "Who was called to the witness box in the court?", ans: "Ram Singh-070 robot" },
    { chapter: 2, marks: 1, q: "Why did the lawyer feel that the robot's system was tampered with?", ans: "Because the robot did not provide certain information" },
    { chapter: 2, marks: 1, q: "What threat did Prem Chopra give to the robot?", ans: "To defuse its system" },
    { chapter: 2, marks: 1, q: "Why did the robot hide its master's information?", ans: "Because it did not want to disobey its master" },
    { chapter: 2, marks: 1, q: "Why did the robot defuse itself?", ans: "So that humans would not be harmed and the master would not be betrayed" },
    { chapter: 2, marks: 1, q: "Who was shocked by the robot breaking into pieces?", ans: "Counsel Goel" },
    { chapter: 2, marks: 1, q: "Whom did the judge find guilty?", ans: "Prem Chopra" },
    { chapter: 2, marks: 1, q: "What was hanging around the neck of the Ram Singh robot?", ans: "A license number plate" },
    { chapter: 2, marks: 1, q: "Under which charge was the crime registered in the court?", ans: "Theft" },
    { chapter: 2, marks: 1, q: "\"Robots never lie\" - who says this sentence?", ans: "Prem Chopra" },
    { chapter: 2, marks: 1, q: "How did Ram Singh-070 meet its end?", ans: "It self-destructed" },
    { chapter: 2, marks: 1, q: "Where did Prem Chopra sign during the purchase of the Ram Singh-070 robot?", ans: "On the deed of sale and contract" },

// ---------------- Chapter 3: An Interview with Arun Krishnamurthy (Std 10 English) ----------------
    { chapter: 3, marks: 1, q: "Which NGO did Arun Krishnamurthy found?", ans: "EFI (Environmentalist Foundation of India)" },
    { chapter: 3, marks: 1, q: "At what age did Arun found EFI?", ans: "At the age of 17" },
    { chapter: 3, marks: 1, q: "What was in the lake near Arun's house?", ans: "A lot of dirt and garbage" },
    { chapter: 3, marks: 1, q: "What menace increased in the lake due to the dirt?", ans: "Mosquitoes" },
    { chapter: 3, marks: 1, q: "Which lake did Arun clean first?", ans: "The lake next to his house" },
    { chapter: 3, marks: 1, q: "In which cities does Arun's organization work?", ans: "Chennai, Hyderabad, Delhi, Coimbatore, Pondicherry, etc." },
    { chapter: 3, marks: 1, q: "In what did Arun's parents give him full support?", ans: "In the work of saving the environment" },
    { chapter: 3, marks: 1, q: "What did Arun's teachers teach him?", ans: "Humility" },
    { chapter: 3, marks: 1, q: "Which company did Arun quit to start his environmental work?", ans: "Google" },
    { chapter: 3, marks: 1, q: "When did Arun leave his job at Google?", ans: "In 2010" },
    { chapter: 3, marks: 1, q: "What work does the EFI organization do?", ans: "Cleaning lakes and beaches, planting trees, etc." },
    { chapter: 3, marks: 1, q: "What tools does Arun's team use?", ans: "Rakes and spades" },
    { chapter: 3, marks: 1, q: "What does Arun consider himself to be?", ans: "An environmentalist" },
    { chapter: 3, marks: 1, q: "What does Arun's team wear for safety while cleaning a lake?", ans: "Gloves and boots" },
    { chapter: 3, marks: 1, q: "Whom does the garbage thrown into the water harm?", ans: "Aquatic animals" },
    { chapter: 3, marks: 1, q: "According to Arun, how much time does it take to clean a lake?", ans: "From 5 days to 3 months" },
    { chapter: 3, marks: 1, q: "How do school and college students join Arun's organization?", ans: "As volunteers" },
    { chapter: 3, marks: 1, q: "How much time should students give for the environment in a week?", ans: "4 hours (2 hours each on Saturday and Sunday)" },
    { chapter: 3, marks: 1, q: "What does Arun make for environmental awareness?", ans: "Short films and paper bags" },
    { chapter: 3, marks: 1, q: "According to Arun, what do animals teach us?", ans: "To be self-reliant" },
    { chapter: 3, marks: 1, q: "Where did Arun run the campaign to save turtles?", ans: "On the coast of Chennai" },
    { chapter: 3, marks: 1, q: "Where did Arun's team dump the garbage taken out of the lake?", ans: "In a safe place outside the lake" },
    { chapter: 3, marks: 1, q: "According to Arun, what is water?", ans: "The basis of life" },
    { chapter: 3, marks: 1, q: "Which organization offers fellowships to the youth?", ans: "EFI" },
    { chapter: 3, marks: 1, q: "What was special about Arun's school and college?", ans: "Both had plenty of green cover" },
    { chapter: 3, marks: 1, q: "Who is Arun still connected with even after leaving his job at Google?", ans: "With his old friends" },
    { chapter: 3, marks: 1, q: "Which aquatic animals did Arun specifically mention?", ans: "Turtles and snakes" },
    { chapter: 3, marks: 1, q: "What does Arun advise people not to do?", ans: "Not to throw garbage in the water" },
    { chapter: 3, marks: 1, q: "What does Arun's organization manufacture from garbage?", ans: "Dustbins" },
    { chapter: 3, marks: 1, q: "According to Arun, how should every person be?", ans: "Environmentally aware" },

// ---------------- Chapter 4: A Wonderful Creation (Std 10 English) ----------------
    { chapter: 4, marks: 1, q: "Who is the creator in the lesson 'A Wonderful Creation'?", ans: "God (The Lord)" },
    { chapter: 4, marks: 1, q: "For how many consecutive days had God been working?", ans: "On the sixth day" },
    { chapter: 4, marks: 1, q: "Whose model was God making?", ans: "Of a mother" },
    { chapter: 4, marks: 1, q: "Who came to meet God?", ans: "An angel" },
    { chapter: 4, marks: 1, q: "How should all the parts of the mother's model be?", ans: "Movable and replaceable" },
    { chapter: 4, marks: 1, q: "What did God say about the mother's lap?", ans: "It disappears when she stands up" },
    { chapter: 4, marks: 1, q: "How many pairs of hands must a mother have?", ans: "Six pairs of hands" },
    { chapter: 4, marks: 1, q: "How many pairs of eyes must a mother have?", ans: "Three pairs of eyes" },
    { chapter: 4, marks: 1, q: "What is the function of the first pair of the mother's eyes?", ans: "To see the child through closed doors" },
    { chapter: 4, marks: 1, q: "What is the function of the second pair of eyes?", ans: "To show love to the child without speaking" },
    { chapter: 4, marks: 1, q: "What is the function of the third pair of eyes?", ans: "To know all the secrets of the child" },
    { chapter: 4, marks: 1, q: "What did the angel request God?", ans: "To take rest" },
    { chapter: 4, marks: 1, q: "What power does a mother's kiss have?", ans: "It can cure everything from a broken leg to a broken heart" },
    { chapter: 4, marks: 1, q: "What kind of food can a mother manage with?", ans: "Any food available" },
    { chapter: 4, marks: 1, q: "How did the mother's model feel to the angel upon touching?", ans: "Very soft" },
    { chapter: 4, marks: 1, q: "What else did God call the mother along with being soft?", ans: "Tough" },
    { chapter: 4, marks: 1, q: "What all can a mother do?", ans: "She can think, reason (compromise), and endure" },
    { chapter: 4, marks: 1, q: "What did the angel see on the cheek of the mother's model?", ans: "A tear" },
    { chapter: 4, marks: 1, q: "What did the angel ask about the tear?", ans: "What is this? (In surprise)" },
    { chapter: 4, marks: 1, q: "What did God answer about the tear?", ans: "I did not put it there, it is a miracle" },
    { chapter: 4, marks: 1, q: "Why might a tear come from a mother's eye?", ans: "For pain, joy, pride, or loneliness" },
    { chapter: 4, marks: 1, q: "How did the angel describe the Lord's creation?", ans: "Wonderful" },
    { chapter: 4, marks: 1, q: "What was God highly focused on while making the mother's model?", ans: "He was very busy (concentrated)" },
    { chapter: 4, marks: 1, q: "What can a mother do with six pairs of hands?", ans: "She can do all the family chores without complaining" },
    { chapter: 4, marks: 1, q: "What can a mother do when she is sick?", ans: "She can heal herself" },
    { chapter: 4, marks: 1, q: "\"Lord, this is an impossible task\" - who says this?", ans: "The angel" },
    { chapter: 4, marks: 1, q: "What does the word 'Replaceable' mean?", ans: "That which can be changed (replaced)" },
    { chapter: 4, marks: 1, q: "Which qualities of a mother are shown in the lesson?", ans: "Love, sacrifice, tolerance, and affection" },
    { chapter: 4, marks: 1, q: "In what did God put his best ideas?", ans: "In the model of the mother" },
    { chapter: 4, marks: 1, q: "At the end of the lesson, what does the angel feel about the Lord's work?", ans: "Great wonder and respect" },

// ---------------- Chapter 5: Playing with Fire (Std 10 English) ----------------
    { chapter: 5, marks: 1, q: "What is the science of making fireworks called?", ans: "Pyrotechnics" },
    { chapter: 5, marks: 1, q: "From which language are the words 'Pyrotechnics' derived?", ans: "Greek language" },
    { chapter: 5, marks: 1, q: "What does the Greek word 'Pyr' mean?", ans: "Fire" },
    { chapter: 5, marks: 1, q: "What does the Greek word 'technics' mean?", ans: "Art" },
    { chapter: 5, marks: 1, q: "What else is included in pyrotechnics besides fireworks?", ans: "Safety match" },
    { chapter: 5, marks: 1, q: "What is a safety match considered to be?", ans: "A special pyrotechnic device" },
    { chapter: 5, marks: 1, q: "What is the basic material used in fireworks called?", ans: "Black powder or gunpowder" },
    { chapter: 5, marks: 1, q: "In which country is black powder believed to have been invented?", ans: "In India" },
    { chapter: 5, marks: 1, q: "Which book mentions substances similar to fireworks?", ans: "Sukraniti" },
    { chapter: 5, marks: 1, q: "How many years old is the book Sukraniti?", ans: "More than 2000 years" },
    { chapter: 5, marks: 1, q: "Who is believed to have given the formula for black powder to the world?", ans: "Roger Bacon" },
    { chapter: 5, marks: 1, q: "Of which country was Roger Bacon a monk?", ans: "England (An English monk)" },
    { chapter: 5, marks: 1, q: "In which year did Roger Bacon reveal the formula of black powder?", ans: "In 1242" },
    { chapter: 5, marks: 1, q: "In which language did Roger Bacon write the formula of black powder?", ans: "In code language" },
    { chapter: 5, marks: 1, q: "Which three substances are mixed in black powder?", ans: "Potassium nitrate, charcoal, and sulfur" },
    { chapter: 5, marks: 1, q: "What is the ratio of black powder?", ans: "75:15:10" },
    { chapter: 5, marks: 1, q: "What causes the light when a firework explodes?", ans: "Due to luminescence" },
    { chapter: 5, marks: 1, q: "Where is the largest production of fireworks in India?", ans: "In Sivakasi" },
    { chapter: 5, marks: 1, q: "In which state is Sivakasi located?", ans: "Tamil Nadu" },
    { chapter: 5, marks: 1, q: "When did the manufacturing of fireworks begin in Sivakasi?", ans: "After Independence" },
    { chapter: 5, marks: 1, q: "For which festival are fireworks made in Sivakasi?", ans: "For Diwali" },
    { chapter: 5, marks: 1, q: "What is the biggest danger in the production of fireworks?", ans: "Catching fire" },
    { chapter: 5, marks: 1, q: "By whom is the process of making fireworks mostly done?", ans: "By hand (Manual labor)" },
    { chapter: 5, marks: 1, q: "What should not be worn while bursting fireworks?", ans: "Nylon or loose clothes" },
    { chapter: 5, marks: 1, q: "What should be avoided while bursting fireworks?", ans: "Holding them in hand" },
    { chapter: 5, marks: 1, q: "What do the Chinese consider black powder to be?", ans: "Their gift to the world" },
    { chapter: 5, marks: 1, q: "How should the temperature be to produce colors from fireworks?", ans: "Very high" },
    { chapter: 5, marks: 1, q: "What effects are seen in a safety match?", ans: "Heat, smoke, light, gas, and sound" },
    { chapter: 5, marks: 1, q: "According to the basic principle of pyrotechnics, what happens when a fuel is heated?", ans: "It burns with oxygen to produce fire" },
    { chapter: 5, marks: 1, q: "In modern times, how are different colors added to fireworks?", ans: "By metallic powders" },

    // ---------------- Chapter 6: I Love You, Teacher (Std 10 English) ----------------
    { chapter: 6, marks: 1, q: "Whose life is this lesson based on?", ans: "Helen Keller" },
    { chapter: 6, marks: 1, q: "What were Helen Keller's physical disabilities?", ans: "She was blind and deaf" },
    { chapter: 6, marks: 1, q: "At what age did Helen become blind and deaf?", ans: "At a very young age (in childhood)" },
    { chapter: 6, marks: 1, q: "What could Helen not learn because of being deaf?", ans: "To speak" },
    { chapter: 6, marks: 1, q: "Whom did Helen's parents contact?", ans: "Miss Anne Sullivan" },
    { chapter: 6, marks: 1, q: "Who was Miss Sullivan?", ans: "A teacher for the blind and deaf" },
    { chapter: 6, marks: 1, q: "What did Miss Sullivan teach Helen first?", ans: "Spelling words by touching hands (Manual alphabet)" },
    { chapter: 6, marks: 1, q: "Which was the first word Helen learned to spell?", ans: "DOLL" },
    { chapter: 6, marks: 1, q: "What was the second important stage for Helen?", ans: "Learning to speak through touch" },
    { chapter: 6, marks: 1, q: "Where did the teacher put Helen's hand?", ans: "Under a water pump in the flowing water" },
    { chapter: 6, marks: 1, q: "What word did the teacher spell on Helen's hand while touching the water?", ans: "WATER" },
    { chapter: 6, marks: 1, q: "How did Helen learn to speak?", ans: "By touching the vibrations of the teacher's lips and throat" },
    { chapter: 6, marks: 1, q: "Which institution did Helen join in 1890?", ans: "Perkins Institution" },
    { chapter: 6, marks: 1, q: "Which languages did Helen learn?", ans: "Latin, German, and French" },
    { chapter: 6, marks: 1, q: "Where was Helen admitted in 1896?", ans: "Cambridge School for Young Ladies (Massachusetts)" },
    { chapter: 6, marks: 1, q: "From which college did Helen complete her graduation?", ans: "Radcliffe College" },
    { chapter: 6, marks: 1, q: "Who was the first deaf-blind person to get a Bachelor of Arts degree?", ans: "Helen Keller" },
    { chapter: 6, marks: 1, q: "What major tragedy happened in Helen's life?", ans: "Her teacher Miss Sullivan lost her eyesight" },
    { chapter: 6, marks: 1, q: "Whom did Miss Sullivan continue to teach without caring for her own eyes?", ans: "Helen Keller" },
    { chapter: 6, marks: 1, q: "What happened to Miss Sullivan in 1935?", ans: "She became completely blind" },
    { chapter: 6, marks: 1, q: "How did Helen take notes in college?", ans: "In Braille or on a typewriter" },
    { chapter: 6, marks: 1, q: "When did Helen's father pass away?", ans: "When Helen was studying in college" },
    { chapter: 6, marks: 1, q: "Where was Helen's first poem or article published?", ans: "In a magazine" },
    { chapter: 6, marks: 1, q: "Who helped Helen in her writing work?", ans: "Her teacher Miss Sullivan" },





// ---------------- Chapter 6: I Love You, Teacher (Std 10 English) ----------------
    { chapter: 6, marks: 1, q: "On whose life is this lesson based?", ans: "Helen Keller" },
    { chapter: 6, marks: 1, q: "What were Helen Keller's physical disabilities?", ans: "She was blind and deaf" },
    { chapter: 6, marks: 1, q: "At what age did Helen become blind and deaf?", ans: "At a very young age (in her childhood)" },
    { chapter: 6, marks: 1, q: "What could Helen not learn because she was deaf?", ans: "She could not learn to speak" },
    { chapter: 6, marks: 1, q: "Whom did Helen's parents contact for help?", ans: "Miss Anne Sullivan" },
    { chapter: 6, marks: 1, q: "Who was Miss Anne Sullivan?", ans: "A teacher for the deaf and blind" },
    { chapter: 6, marks: 1, q: "What did Miss Sullivan teach Helen first?", ans: "Finger movements on the palm (Manual alphabet)" },
    { chapter: 6, marks: 1, q: "Which was the first word Helen learned to spell?", ans: "DOLL" },
    { chapter: 6, marks: 1, q: "What did Helen feel when she successfully spelled 'DOLL'?", ans: "She felt full of joy and pride" },
    { chapter: 6, marks: 1, q: "What was the second important stage of learning for Helen?", ans: "Learning to speak based on the sense of touch" },
    { chapter: 6, marks: 1, q: "Where did the teacher put Helen's hand to teach her the word 'water'?", ans: "Under the flowing water of a water pump" },
    { chapter: 6, marks: 1, q: "What did the teacher spell on Helen's palm while touching the water?", ans: "W-A-T-E-R" },
    { chapter: 6, marks: 1, q: "How did Helen learn to speak?", ans: "By touching her teacher's lips and the vibration in her throat" },
    { chapter: 6, marks: 1, q: "What awakened Helen's soul?", ans: "The word 'WATER'" },
    { chapter: 6, marks: 1, q: "In which year did Helen join the Perkins Institution?", ans: "In 1890" },
    { chapter: 6, marks: 1, q: "Which languages did Helen learn at the Cambridge School?", ans: "Latin, German, and French" },
    { chapter: 6, marks: 1, q: "In 1896, where did Helen take admission?", ans: "Cambridge School for Young Ladies in Massachusetts" },
    { chapter: 6, marks: 1, q: "From which college did Helen complete her graduation?", ans: "Radcliffe College" },
    { chapter: 6, marks: 1, q: "Who was the first deaf-blind person to earn a Bachelor of Arts degree?", ans: "Helen Keller" },
    { chapter: 6, marks: 1, q: "What happened to Helen's father when she was in Radcliffe College?", ans: "He passed away" },
    { chapter: 6, marks: 1, q: "How did Helen take notes in college?", ans: "She typed them on a typewriter" },
    { chapter: 6, marks: 1, q: "Who helped Helen write her first article/poem?", ans: "Miss Anne Sullivan" },
    { chapter: 6, marks: 1, q: "What major tragedy happened in Helen's life later?", ans: "Her teacher Miss Sullivan's eyesight became weak" },
    { chapter: 6, marks: 1, q: "Did Miss Sullivan stop teaching Helen when her eyes became weak?", ans: "No, she ignored her health to continue teaching Helen" },
    { chapter: 6, marks: 1, q: "In which year did Miss Sullivan become completely blind?", ans: "In 1935" },
    { chapter: 6, marks: 1, q: "For whom did Miss Sullivan sacrifice her eyesight?", ans: "For her student, Helen Keller" },
    { chapter: 6, marks: 1, q: "How did Helen feel about her teacher's sacrifice?", ans: "She was deeply pained and grateful" },
    { chapter: 6, marks: 1, q: "What bounded Helen and Miss Sullivan together?", ans: "A deep bond of love" },
    { chapter: 6, marks: 1, q: "What did Helen say at the end of the lesson?", ans: "I love you, teacher" },
    { chapter: 6, marks: 1, q: "What is the main message of this chapter?", ans: "Dedication and love can overcome the greatest hurdles" },

// ---------------- Chapter 7: Kach and Dev (Std 10 English) ----------------
    { chapter: 7, marks: 1, q: "Who were always fighting against each other in mythological times?", ans: "The Devas (Gods) and the Asuras (Demons)" },
    { chapter: 7, marks: 1, q: "Who was the chief priest or guru of the Asuras?", ans: "Shukracharya" },
    { chapter: 7, marks: 1, q: "Who was the chief priest or guru of the Devas?", ans: "Brihaspati" },
    { chapter: 7, marks: 1, q: "What great secret did Shukracharya know?", ans: "Sanjivani Vidya (The magic formula to bring dead to life)" },
    { chapter: 7, marks: 1, q: "What advantage did the Asuras have over the Devas in battles?", ans: "Shukracharya brought the dead Asuras back to life" },
    { chapter: 7, marks: 1, q: "What did the Devas decide to do to counter the Asuras?", ans: "They decided to send someone to learn Sanjivani Vidya" },
    { chapter: 7, marks: 1, q: "Who was chosen by the Devas to go to Shukracharya?", ans: "Kach, the son of Brihaspati" },
    { chapter: 7, marks: 1, q: "For how many years did Kach promise to serve Shukracharya?", ans: "For one thousand years" },
    { chapter: 7, marks: 1, q: "Who was Devayani?", ans: "The beautiful daughter of Shukracharya" },
    { chapter: 7, marks: 1, q: "How did Devayani feel about Kach?", ans: "She fell in love with him" },
    { chapter: 7, marks: 1, q: "What was Kach's daily routine at Shukracharya's ashram?", ans: "Bringing firewood, gathering flowers, and tending cows" },
    { chapter: 7, marks: 1, q: "Why were the Asuras unhappy with Kach living in their guru's ashram?", ans: "They suspected he was there to steal the Sanjivani Vidya" },
    { chapter: 7, marks: 1, q: "How many times did the Asuras kill Kach?", ans: "Three times" },
    { chapter: 7, marks: 1, q: "What did the Asuras do to Kach the first time they killed him?", ans: "They cut his body into pieces and fed them to wolves and jackals" },
    { chapter: 7, marks: 1, q: "Who requested Shukracharya to bring Kach back to life every time?", ans: "Devayani" },
    { chapter: 7, marks: 1, q: "How did Shukracharya revive Kach the first time?", ans: "By using Sanjivani Vidya and calling his name" },
    { chapter: 7, marks: 1, q: "What did the Asuras do to Kach the second time?", ans: "They killed him, ground his body into paste, and mixed it in ocean water" },
    { chapter: 7, marks: 1, q: "What did the Asuras do the third time to ensure Kach couldn't be revived easily?", ans: "They burnt him to ashes and mixed the ashes in Shukracharya's wine" },
    { chapter: 7, marks: 1, q: "Where was Kach when Shukracharya called him the third time?", ans: "Inside Shukracharya's stomach" },
    { chapter: 7, marks: 1, q: "What was the dilemma for Shukracharya when Kach was in his stomach?", ans: "If Kach comes out, Shukracharya dies; if he stays, Kach is lost" },
    { chapter: 7, marks: 1, q: "What solution did Shukracharya find?", ans: "He taught the Sanjivani Vidya to Kach while he was in his stomach" },
    { chapter: 7, marks: 1, q: "What did Kach do immediately after coming out of Shukracharya's stomach?", ans: "He used the Sanjivani Vidya to bring Shukracharya back to life" },
    { chapter: 7, marks: 1, q: "What did Devayani ask Kach when his training was complete?", ans: "She asked him to marry her" },
    { chapter: 7, marks: 1, q: "Did Kach accept Devayani's proposal?", ans: "No, he refused" },
    { chapter: 7, marks: 1, q: "Why did Kach refuse to marry Devayani?", ans: "Because he considered her his sister (both were 'born' from Shukracharya)" },
    { chapter: 7, marks: 1, q: "How did Devayani react to Kach's refusal?", ans: "She became very angry and cursed him" },
    { chapter: 7, marks: 1, q: "What curse did Devayani give to Kach?", ans: "That he would not be able to practice the Sanjivani Vidya himself" },
    { chapter: 7, marks: 1, q: "How did Kach respond to the curse?", ans: "He said he would teach it to someone else who could use it" },
    { chapter: 7, marks: 1, q: "What was the result of Kach's mission?", ans: "He successfully brought the Sanjivani Vidya to the Devas" },
    { chapter: 7, marks: 1, q: "How did the Devas welcome Kach?", ans: "With great joy and honor" },

// ---------------- Chapter 8: Our Feathered Friends (Std 10 English) ----------------
    { chapter: 8, marks: 1, q: "Who came to visit Mitra's family?", ans: "Devangi" },
    { chapter: 8, marks: 1, q: "What is Devangi studying?", ans: "Zoology" },
    { chapter: 8, marks: 1, q: "Where is Devangi studying?", ans: "At M.S. University, Vadodara" },
    { chapter: 8, marks: 1, q: "Who is very interested in knowing about birds?", ans: "Subhangi (Mitra's younger sister)" },
    { chapter: 8, marks: 1, q: "Which bird does Subhangi ask about first?", ans: "The Tailorbird" },
    { chapter: 8, marks: 1, q: "Why is the Tailorbird called so?", ans: "Because it stitches its nest using leaves" },
    { chapter: 8, marks: 1, q: "What is the female Tailorbird's main job?", ans: "To lay eggs and incubate them" },
    { chapter: 8, marks: 1, q: "What is the second bird they discuss?", ans: "The Weaver bird (Baya)" },
    { chapter: 8, marks: 1, q: "Who builds the nest in the Weaver bird species?", ans: "The male Weaver bird" },
    { chapter: 8, marks: 1, q: "What happens if the female Weaver bird rejects the nest?", ans: "The male has to abandon it and build a new one" },
    { chapter: 8, marks: 1, q: "Why do Weaver birds prefer thorny trees for nests?", ans: "To protect their eggs from predators" },
    { chapter: 8, marks: 1, q: "Which bird is known as the 'scavenger' of nature?", ans: "The Vulture" },
    { chapter: 8, marks: 1, q: "Why are vultures important for the environment?", ans: "They eat dead animals and keep the environment clean" },
    { chapter: 8, marks: 1, q: "Why is the vulture population decreasing in India?", ans: "Due to a medicine called Diclofenac used for cattle" },
    { chapter: 8, marks: 1, q: "How does Diclofenac kill vultures?", ans: "It causes kidney failure when they eat the treated dead cattle" },
    { chapter: 8, marks: 1, q: "What is the Gujarati name for the Indian Grey Hornbill?", ans: "Chilotro" },
    { chapter: 8, marks: 1, q: "Where does the Indian Grey Hornbill make its nest?", ans: "In the hollows of large trees" },
    { chapter: 8, marks: 1, q: "How does the male Hornbill feed the female during incubation?", ans: "Through a small slit in the sealed nest" },
    { chapter: 8, marks: 1, q: "What does the female Hornbill use to seal the nest hole?", ans: "Mud and her own droppings" },
    { chapter: 8, marks: 1, q: "Which migratory bird is mentioned as coming from cold regions?", ans: "The Pelican / Flamingo (Migratory birds in general)" },
    { chapter: 8, marks: 1, q: "Why do migratory birds travel long distances?", ans: "To escape extreme cold and find food" },
    { chapter: 8, marks: 1, q: "What helps birds fly long distances without getting lost?", ans: "Their internal magnetic compass and the position of the sun/stars" },
    { chapter: 8, marks: 1, q: "Which bird is the state bird of Gujarat?", ans: "The Greater Flamingo (Surkhab)" },
    { chapter: 8, marks: 1, q: "What color is the Greater Flamingo?", ans: "Light pink" },
    { chapter: 8, marks: 1, q: "Where do Flamingos make their nests in Gujarat?", ans: "In the Rann of Kutch (Flamingo City)" },
    { chapter: 8, marks: 1, q: "What is the nest of a Flamingo made of?", ans: "Mud (It looks like a small mound)" },
    { chapter: 8, marks: 1, q: "What message does Devangi give at the end?", ans: "We should protect birds and their habitats" },
    { chapter: 8, marks: 1, q: "Why do birds sing in the morning?", ans: "To claim their territory and attract mates" },
    { chapter: 8, marks: 1, q: "What do birds use their beaks for?", ans: "To catch food, build nests, and preen their feathers" },
    { chapter: 8, marks: 1, q: "How can we help birds in summer?", ans: "By keeping water pots and grain for them" },

// ---------------- Chapter 9: Tune Up, O Teens (Std 10 English) ----------------
    { chapter: 9, marks: 1, q: "What is the theme of the seminar in the chapter?", ans: "Bring out your best" },
    { chapter: 9, marks: 1, q: "Who organized the seminar?", ans: "Anand Vihar School and the NGO 'Saraswati'" },
    { chapter: 9, marks: 1, q: "For whom was the seminar organized?", ans: "For students of class 10 and 12 and their parents" },
    { chapter: 9, marks: 1, q: "Who was the well-known counselor present at the seminar?", ans: "Mr. Saurabh Bakshi" },
    { chapter: 9, marks: 1, q: "Who was the clinical psychologist at the seminar?", ans: "Dr. Mrs. Shalini Shah" },
    { chapter: 9, marks: 1, q: "What was the first question asked by a student named Bharat?", ans: "How to improve memory and concentration" },
    { chapter: 9, marks: 1, q: "What technique did Dr. Shah suggest for better concentration?", ans: "Meditation and focusing on the breath" },
    { chapter: 9, marks: 1, q: "What should students avoid while studying?", ans: "Distractions like mobile phones and TV" },
    { chapter: 9, marks: 1, q: "What did a parent ask about their child's diet during exams?", ans: "What kind of food is best during exam days" },
    { chapter: 9, marks: 1, q: "What diet was recommended by the experts?", ans: "Light, healthy, and easily digestible food (fruits, vegetables, nuts)" },
    { chapter: 9, marks: 1, q: "Why should students avoid heavy and oily food before exams?", ans: "Because it makes them feel sleepy and lethargic" },
    { chapter: 9, marks: 1, q: "Who asked a question about exam stress and blanking out?", ans: "A student named Anuj" },
    { chapter: 9, marks: 1, q: "Why do students go 'blank' during exams?", ans: "Due to extreme fear and anxiety" },
    { chapter: 9, marks: 1, q: "What is the advice to overcome the fear of exams?", ans: "To treat exams as a normal part of life, not a matter of life and death" },
    { chapter: 9, marks: 1, q: "How much sleep is recommended for a teenager during exams?", ans: "At least 7 to 8 hours of sound sleep" },
    { chapter: 9, marks: 1, q: "What did Mr. Bakshi say about comparing oneself with others?", ans: "It is harmful; one should only compete with oneself" },
    { chapter: 9, marks: 1, q: "What problem did a girl named Rucha share?", ans: "She said her parents expect too much from her" },
    { chapter: 9, marks: 1, q: "What advice was given to parents regarding expectations?", ans: "To set realistic goals based on the child's aptitude, not societal pressure" },
    { chapter: 9, marks: 1, q: "Why is taking short breaks during study important?", ans: "To refresh the brain and maintain focus" },
    { chapter: 9, marks: 1, q: "How long should a typical study session be before taking a break?", ans: "Around 40 to 45 minutes" },
    { chapter: 9, marks: 1, q: "What role do hobbies play during exam preparation?", ans: "They act as stress-busters and relax the mind" },
    { chapter: 9, marks: 1, q: "What did the experts say about last-minute cramming?", ans: "It creates confusion; revision should be systematic" },
    { chapter: 9, marks: 1, q: "How should a student manage time effectively?", ans: "By making a realistic timetable and sticking to it" },
    { chapter: 9, marks: 1, q: "What is 'positive self-talk'?", ans: "Encouraging oneself and believing in one's abilities" },
    { chapter: 9, marks: 1, q: "What should parents do on the day of the exam?", ans: "Create a calm atmosphere and wish the child good luck without pressure" },
    { chapter: 9, marks: 1, q: "What is the importance of drinking water during studies?", ans: "It keeps the brain hydrated and active" },
    { chapter: 9, marks: 1, q: "Who concluded the seminar and thanked the experts?", ans: "The principal of the school" },
    { chapter: 9, marks: 1, q: "What is the main message for teenagers in this chapter?", ans: "To tune up their minds and bodies positively for challenges" },
    { chapter: 9, marks: 1, q: "What is the key to success according to the seminar?", ans: "Hard work, proper planning, and a stress-free mind" },
    { chapter: 9, marks: 1, q: "What word is used for 'the ability to understand one's own feelings'?", ans: "Self-awareness" },

// ---------------- Chapter 10: Test of True Love (Std 10 English) ----------------
    { chapter: 10, marks: 1, q: "Who is the main character of the story?", ans: "Lieutenant John Blandford" },
    { chapter: 10, marks: 1, q: "Where was Lieutenant Blandford waiting?", ans: "At Grand Central Station, New York" },
    { chapter: 10, marks: 1, q: "What time was it when Blandford was looking at the clock?", ans: "Six minutes to six" },
    { chapter: 10, marks: 1, q: "Whom was John Blandford waiting to meet?", ans: "Hollis Meynell" },
    { chapter: 10, marks: 1, q: "For how long had John and Hollis been corresponding (writing letters)?", ans: "For 13 months" },
    { chapter: 10, marks: 1, q: "How did John first learn about Hollis Meynell?", ans: "He read her notes in a book he bought" },
    { chapter: 10, marks: 1, q: "What was the title of the book in which John found her notes?", ans: "Of Human Bondage" },
    { chapter: 10, marks: 1, q: "What did John request from Hollis in his letters?", ans: "A photograph of her" },
    { chapter: 10, marks: 1, q: "Did Hollis send her photograph to John?", ans: "No, she refused" },
    { chapter: 10, marks: 1, q: "What reason did Hollis give for not sending her picture?", ans: "She said true love doesn't depend on physical beauty" },
    { chapter: 10, marks: 1, q: "How were they supposed to identify each other at the station?", ans: "By a red rose and the book 'Of Human Bondage'" },
    { chapter: 10, marks: 1, q: "What was John holding to identify himself?", ans: "The book 'Of Human Bondage'" },
    { chapter: 10, marks: 1, q: "What was Hollis supposed to wear to identify herself?", ans: "A red rose pinned to her coat" },
    { chapter: 10, marks: 1, q: "As the clock struck six, whom did John see first?", ans: "A beautiful young woman in a green suit" },
    { chapter: 10, marks: 1, q: "Did the beautiful young woman have a red rose?", ans: "No, she didn't have a red rose" },
    { chapter: 10, marks: 1, q: "Who was walking behind the beautiful young woman?", ans: "An older woman, past forty" },
    { chapter: 10, marks: 1, q: "What did John notice on the older woman's coat?", ans: "A red rose" },
    { chapter: 10, marks: 1, q: "How did John feel when he saw the older woman with the rose?", ans: "He felt a bit disappointed but respected his commitment" },
    { chapter: 10, marks: 1, q: "Did John ignore the older woman and go after the young beauty?", ans: "No, he walked towards the older woman" },
    { chapter: 10, marks: 1, q: "What did John do when he approached the older woman?", ans: "He greeted her respectfully and introduced himself" },
    { chapter: 10, marks: 1, q: "What did John ask the older woman?", ans: "He invited her to join him for dinner" },
    { chapter: 10, marks: 1, q: "How did the older woman react to John's invitation?", ans: "She smiled and seemed confused" },
    { chapter: 10, marks: 1, q: "What secret did the older woman reveal to John?", ans: "She said the young woman in the green suit asked her to wear the rose" },
    { chapter: 10, marks: 1, q: "What was the young woman's instruction to the older woman?", ans: "If he invites you to dinner, tell him I am waiting at the restaurant across the street" },
    { chapter: 10, marks: 1, q: "Why did Hollis Meynell arrange this situation?", ans: "To test John's true character and love" },
    { chapter: 10, marks: 1, q: "Did John pass the test of true love?", ans: "Yes, he passed it successfully" },
    { chapter: 10, marks: 1, q: "What did the test prove about John Blandford?", ans: "That his love was genuine and not based just on looks" },
    { chapter: 10, marks: 1, q: "Where was the real Hollis Meynell waiting?", ans: "At the restaurant across the street" },
    { chapter: 10, marks: 1, q: "What quality of John is highlighted in this story?", ans: "Loyalty and inner goodness" },
    { chapter: 10, marks: 1, q: "What is the central idea of the story 'Test of True Love'?", ans: "True love goes beyond physical appearance and values the soul" },


// ---------------- Chapter 11: My Song (Poem 1) ----------------
    { chapter: 11, marks: 1, q: "Who is the poet of the poem 'My Song'?", ans: "Rabindranath Tagore" },
    { chapter: 11, marks: 1, q: "To whom is the poet singing this song?", ans: "To his child" },
    { chapter: 11, marks: 1, q: "What will the song wrap around the child?", ans: "Its music" },
    { chapter: 11, marks: 1, q: "What is the music of the song compared to?", ans: "The fond arms of love" },
    { chapter: 11, marks: 1, q: "What will the song touch?", ans: "The child's forehead" },
    { chapter: 11, marks: 1, q: "How will the song touch the child's forehead?", ans: "Like a kiss of blessing" },
    { chapter: 11, marks: 1, q: "What will the song do when the child is alone?", ans: "It will sit by the child's side and whisper in the ear" },
    { chapter: 11, marks: 1, q: "What will the song do when the child is in a crowd?", ans: "It will fence the child about with aloofness" },
    { chapter: 11, marks: 1, q: "What does the word 'aloofness' mean here?", ans: "Protection from the crowd / Keeping a safe distance" },
    { chapter: 11, marks: 1, q: "What will the song be like for the child's dreams?", ans: "It will be like a pair of wings" },
    { chapter: 11, marks: 1, q: "Where will the song transport the child's heart?", ans: "To the verge of the unknown" },
    { chapter: 11, marks: 1, q: "What will the song be like when the night is dark?", ans: "Like the faithful star overhead" },
    { chapter: 11, marks: 1, q: "Where will the song sit when the child travels?", ans: "In the pupils of the child's eyes" },
    { chapter: 11, marks: 1, q: "Where will the song carry the child's sight?", ans: "Into the heart of things" },
    { chapter: 11, marks: 1, q: "What happens when the poet's voice is silent in death?", ans: "The song will speak in the child's living heart" },
    { chapter: 11, marks: 1, q: "Who will become silent in death according to the poem?", ans: "The poet (the parent)" },
    { chapter: 11, marks: 1, q: "Where does the song live even after the poet's death?", ans: "In the living heart of the child" },
    { chapter: 11, marks: 1, q: "What does the 'kiss of blessing' represent?", ans: "The parent's deep love and good wishes" },
    { chapter: 11, marks: 1, q: "What does 'faithful star' symbolize?", ans: "Guidance in dark or difficult times" },
    { chapter: 11, marks: 1, q: "Does the song physically touch the child?", ans: "No, it is a spiritual and emotional connection" },
    { chapter: 11, marks: 1, q: "What does the song provide in times of loneliness?", ans: "Companionship and comfort" },
    { chapter: 11, marks: 1, q: "What does the song protect the child from?", ans: "The negative influence of the crowd" },
    { chapter: 11, marks: 1, q: "What does the word 'fond' mean in the poem?", ans: "Loving and affectionate" },
    { chapter: 11, marks: 1, q: "What does 'verge of the unknown' mean?", ans: "The edge of new and undiscovered things" },
    { chapter: 11, marks: 1, q: "How is the parent's presence felt after death?", ans: "Through the words of this song" },
    { chapter: 11, marks: 1, q: "Which sense organ is mentioned to see the 'heart of things'?", ans: "The eyes (pupils)" },
    { chapter: 11, marks: 1, q: "What does the song give to the child's dreams?", ans: "Flight and freedom (wings)" },
    { chapter: 11, marks: 1, q: "Is the tone of the poem aggressive or soothing?", ans: "Soothing and loving" },
    { chapter: 11, marks: 1, q: "What is the ultimate message of 'My Song'?", ans: "A parent's love and guidance stay with the child forever" },
    { chapter: 11, marks: 1, q: "What will speak when the voice is silent?", ans: "The poet's song" },

// ---------------- Chapter 12: Pencil (Poem 2) ----------------
    { chapter: 12, marks: 1, q: "Who is the poet of the poem 'Pencil'?", ans: "Jayant Parmar" },
    { chapter: 12, marks: 1, q: "Who is the main character in the poem 'Pencil'?", ans: "A little girl" },
    { chapter: 12, marks: 1, q: "What is the little girl doing with the pencil?", ans: "She is lighting it like a candle" },
    { chapter: 12, marks: 1, q: "What does the girl use to sharpen the pencil?", ans: "A sharpener" },
    { chapter: 12, marks: 1, q: "Where is the little girl drawing her pictures?", ans: "On the sky of the white paper" },
    { chapter: 12, marks: 1, q: "What kind of bird has the girl drawn?", ans: "A black bird" },
    { chapter: 12, marks: 1, q: "Where is the black bird flying in her drawing?", ans: "Away with the tree" },
    { chapter: 12, marks: 1, q: "What is the white bear doing in the drawing?", ans: "Looking through blue glasses" },
    { chapter: 12, marks: 1, q: "What color are the bear's glasses?", ans: "Blue" },
    { chapter: 12, marks: 1, q: "Who is driving the airplane in the drawing?", ans: "A monkey" },
    { chapter: 12, marks: 1, q: "Who is having a conversation in the girl's drawing?", ans: "A cow and a flying bird" },
    { chapter: 12, marks: 1, q: "What does the sun in the drawing look like?", ans: "It has only one eye" },
    { chapter: 12, marks: 1, q: "Where is the one-eyed sun drawn?", ans: "On the black tree" },
    { chapter: 12, marks: 1, q: "What is located over the sun in the drawing?", ans: "A patch of cloud" },
    { chapter: 12, marks: 1, q: "What kind of water is the blue fish drinking?", ans: "The water of a 'blue fish' (Air/Water is swapped in surreal art)" },
    { chapter: 12, marks: 1, q: "Wait, what is actually drinking water in the drawing?", ans: "A lion" },
    { chapter: 12, marks: 1, q: "From where is the lion drinking water?", ans: "From a blue cow (or river)" },
    { chapter: 12, marks: 1, q: "Who is drawn on the yellow bird?", ans: "A peacock" },
    { chapter: 12, marks: 1, q: "What is the peacock doing?", ans: "Sitting on a yellow bird" },
    { chapter: 12, marks: 1, q: "How is the girl feeling while drawing these strange pictures?", ans: "She is busy and happy in her imagination" },
    { chapter: 12, marks: 1, q: "Who breaks the girl's imagination?", ans: "The schoolmaster" },
    { chapter: 12, marks: 1, q: "What does the schoolmaster give to the girl?", ans: "Homework" },
    { chapter: 12, marks: 1, q: "How does the girl react when given homework?", ans: "She gets angry" },
    { chapter: 12, marks: 1, q: "What does the angry girl do to the pencil?", ans: "She breaks the tip of the pencil" },
    { chapter: 12, marks: 1, q: "In what state does she break the pencil?", ans: "In anger" },
    { chapter: 12, marks: 1, q: "What remains on the paper after the pencil is broken?", ans: "Only the smoke of an extinguished candle" },
    { chapter: 12, marks: 1, q: "What does the 'extinguished candle' symbolize?", ans: "The end of her joy and imagination" },
    { chapter: 12, marks: 1, q: "What do the weird drawings tell us about the girl?", ans: "She has a very creative and surreal imagination" },
    { chapter: 12, marks: 1, q: "Is the sky on her paper dark or bright?", ans: "It becomes dark like smoke when the pencil breaks" },
    { chapter: 12, marks: 1, q: "What does homework represent in this poem?", ans: "A burden that kills a child's creativity" },

// ---------------- Chapter 13: Growing (Poem 3) ----------------
    { chapter: 13, marks: 1, q: "Who is the poet of the poem 'Growing'?", ans: "Brooke Mueller" },
    { chapter: 13, marks: 1, q: "To whom is the teenager speaking in the poem?", ans: "To her mother" },
    { chapter: 13, marks: 1, q: "What is the speaker going out to fight?", ans: "The battles" },
    { chapter: 13, marks: 1, q: "What does the teenager want to win?", ans: "The battles of life" },
    { chapter: 13, marks: 1, q: "What is the speaker leaving?", ans: "She is leaving home" },
    { chapter: 13, marks: 1, q: "What does the speaker want her mother to do?", ans: "To let her go and not hold her back" },
    { chapter: 13, marks: 1, q: "What does the teenager want to discover?", ans: "What she has to find (her true self)" },
    { chapter: 13, marks: 1, q: "What does the phrase 'to be me' mean?", ans: "To be independent and true to oneself" },
    { chapter: 13, marks: 1, q: "Does the teenager want her mother's physical help?", ans: "No, she says 'keep your hands off'" },
    { chapter: 13, marks: 1, q: "What does the teenager say she is no longer?", ans: "She is not a child anymore" },
    { chapter: 13, marks: 1, q: "What does the mother need to understand?", ans: "That the teenager has grown up" },
    { chapter: 13, marks: 1, q: "Why is the teenager asking her mother to let her go?", ans: "So she can face the world on her own" },
    { chapter: 13, marks: 1, q: "What does the speaker want to do with her own life?", ans: "Live it in her own way" },
    { chapter: 13, marks: 1, q: "What feeling does the teenager express in the first stanza?", ans: "A strong desire for freedom" },
    { chapter: 13, marks: 1, q: "What might the mother be feeling according to the poem?", ans: "Protective and afraid to let go" },
    { chapter: 13, marks: 1, q: "Even though she wants freedom, who does she address the poem to?", ans: "Her mother, showing she still values her" },
    { chapter: 13, marks: 1, q: "What does 'battles' symbolize in the poem?", ans: "Life's challenges and struggles" },
    { chapter: 13, marks: 1, q: "Is the teenager confident about facing the world?", ans: "Yes, she sounds very confident" },
    { chapter: 13, marks: 1, q: "What kind of tone does the phrase 'keep your hands off' set?", ans: "A rebellious but firm tone" },
    { chapter: 13, marks: 1, q: "What age group does this poem perfectly describe?", ans: "Teenagers (adolescents)" },
    { chapter: 13, marks: 1, q: "What is the central theme of 'Growing'?", ans: "The transition from childhood to independent adulthood" },
    { chapter: 13, marks: 1, q: "What does the teenager want the mother to accept?", ans: "Her independence and maturity" },
    { chapter: 13, marks: 1, q: "What does 'leaving' symbolize here?", ans: "Stepping out into the real world" },
    { chapter: 13, marks: 1, q: "What is the teenager determined to do?", ans: "To win her battles" },
    { chapter: 13, marks: 1, q: "Does the teenager want to rely on her mother's protection?", ans: "No" },
    { chapter: 13, marks: 1, q: "What does she want to find?", ans: "Her own path and identity" },
    { chapter: 13, marks: 1, q: "What emotion is common between teenagers and parents during this phase?", ans: "Conflict over freedom vs. protection" },
    { chapter: 13, marks: 1, q: "Why must the mother keep her 'hands off'?", ans: "So the child can learn from her own mistakes" },
    { chapter: 13, marks: 1, q: "What is the ultimate goal of the teenager?", ans: "To be herself ('be me')" },
    { chapter: 13, marks: 1, q: "What is the synonym for 'battles' in the context of life?", ans: "Struggles or challenges" },

// ---------------- Chapter 14: Blind, Deaf Fish (Poem 4) ----------------
    { chapter: 14, marks: 1, q: "Who is the poet of the poem 'Blind, Deaf Fish'?", ans: "Anand Acharya" },
    { chapter: 14, marks: 1, q: "Where does the river flow in the poem?", ans: "In a dark cave" },
    { chapter: 14, marks: 1, q: "What kind of cave is mentioned in the poem?", ans: "A dark cave" },
    { chapter: 14, marks: 1, q: "What kind of bank (shore) does the river have?", ans: "A stony bank" },
    { chapter: 14, marks: 1, q: "Who is sitting on the stony bank?", ans: "A man" },
    { chapter: 14, marks: 1, q: "How is the man described in the poem?", ans: "As old as the sun or older" },
    { chapter: 14, marks: 1, q: "What does 'as old as the sun or older' suggest about the man?", ans: "He is eternal or divine (like God)" },
    { chapter: 14, marks: 1, q: "What is the old man doing on the shore?", ans: "He is weaving a yarn of rainbow" },
    { chapter: 14, marks: 1, q: "What is the color of the yarn the old man is weaving?", ans: "Rainbow-hued (many colors)" },
    { chapter: 14, marks: 1, q: "What else is the old man doing while weaving?", ans: "He is humming a song" },
    { chapter: 14, marks: 1, q: "Who is swimming in the dark river?", ans: "A fish" },
    { chapter: 14, marks: 1, q: "What are the physical defects of the fish?", ans: "It is blind and deaf" },
    { chapter: 14, marks: 1, q: "Does the blind fish see the yarn?", ans: "No, it cannot see the rainbow yarn" },
    { chapter: 14, marks: 1, q: "Does the deaf fish hear the song?", ans: "No, it hears nothing of the song" },
    { chapter: 14, marks: 1, q: "What does the 'dark cave' symbolize in the poem?", ans: "The darkness of human ignorance" },
    { chapter: 14, marks: 1, q: "What does the 'river' symbolize?", ans: "The flow of life" },
    { chapter: 14, marks: 1, q: "Who does the 'old man' represent in the poem?", ans: "The Creator (God) or Time" },
    { chapter: 14, marks: 1, q: "What does the 'yarn of rainbow' represent?", ans: "The beauty and magic of the universe" },
    { chapter: 14, marks: 1, q: "Who does the 'blind, deaf fish' represent?", ans: "Ignorant human beings" },
    { chapter: 14, marks: 1, q: "Why are humans compared to the blind and deaf fish?", ans: "Because they fail to see God's beautiful creation" },
    { chapter: 14, marks: 1, q: "What is the song of the old man like?", ans: "Everlasting (endless)" },
    { chapter: 14, marks: 1, q: "What is the fish doing in the stream?", ans: "Swimming continuously" },
    { chapter: 14, marks: 1, q: "What does the fish miss out on?", ans: "The beautiful song and the rainbow yarn" },
    { chapter: 14, marks: 1, q: "Is the fish aware of the old man's presence?", ans: "No, it is completely unaware" },
    { chapter: 14, marks: 1, q: "What is the tone of the poem?", ans: "Mystical and philosophical" },
    { chapter: 14, marks: 1, q: "What is the synonym for 'humming'?", ans: "Singing softly" },
    { chapter: 14, marks: 1, q: "What does 'yarn' mean in this context?", ans: "Thread used for weaving" },
    { chapter: 14, marks: 1, q: "What message does the poet convey?", ans: "People are too busy in their lives to appreciate the divine beauty around them" },
    { chapter: 14, marks: 1, q: "What are the two contrasting elements in the poem?", ans: "The beautiful creation of God vs. the ignorance of the creature" },
    { chapter: 14, marks: 1, q: "What word is used to describe the bank of the river?", ans: "Stony" }

];
     
