var englishFillInTheBlanksDB_Std10 = [

    // ---------------- Chapter 1: Against the Odds ----------------
    { chapter: 1, marks: 1, q: "The village of Taj Nagar is located near _______. (Gurgaon, Delhi, Rewari)", ans: "Gurgaon" },
    { chapter: 1, marks: 1, q: "The residents of Taj Nagar wanted a _______ station in their village. (bus, railway, police)", ans: "railway" },
    { chapter: 1, marks: 1, q: "The villagers collected _______ lakh rupees to build the railway station. (twenty-one, eleven, twenty-five)", ans: "twenty-one" },
    { chapter: 1, marks: 1, q: "Most of the three thousand people living in Taj Nagar are _______. (teachers, farmers, businessmen)", ans: "farmers" },
    { chapter: 1, marks: 1, q: "The railway refused to build the station saying they did not have _______. (land, funds, permission)", ans: "funds" },
    { chapter: 1, marks: 1, q: "The people of Taj Nagar had been demanding a station for _______ years. (twenty, twenty-five, fifteen)", ans: "twenty-five" },
    { chapter: 1, marks: 1, q: "To build the station, the villagers formed an _______ member committee. (eleven, ten, five)", ans: "eleven" },
    { chapter: 1, marks: 1, q: "The Taj Nagar railway station started operations on 7th January _______. (2008, 2010, 2012)", ans: "2010" },
    { chapter: 1, marks: 1, q: "Sitapur district is located in the state of _______. (Gujarat, Uttar Pradesh, Bihar)", ans: "Uttar Pradesh" },
    { chapter: 1, marks: 1, q: "In Sitapur district, over _______ percent of households were without power. (fifty, sixty, seventy)", ans: "sixty" },
    { chapter: 1, marks: 1, q: "A social enterprise named _______ was working to bring light to Sitapur. (EFI, MGP, NGO)", ans: "MGP" },
    { chapter: 1, marks: 1, q: "MGP connected over _______ customers to solar power mini-grids. (3500, 3000, 2500)", ans: "3500" },
    { chapter: 1, marks: 1, q: "The cost of solar power is _______ than kerosene. (cheaper, costlier, equal)", ans: "cheaper" },
    { chapter: 1, marks: 1, q: "Customers get two LED lights and a mobile charging point for 25 rupees per _______. (month, week, day)", ans: "week" },
    { chapter: 1, marks: 1, q: "The first electrician of the MGP project in the village was _______. (Azaz, Ali, Ahmed)", ans: "Azaz" },
    { chapter: 1, marks: 1, q: "Solar panels are usually installed on a strong, _______ wall. (mud, brick, wood)", ans: "brick" },
    { chapter: 1, marks: 1, q: "Azaz installed the solar panel in a _______ direction to capture sunlight. (North, South, East)", ans: "South" },
    { chapter: 1, marks: 1, q: "Solar light helps the village weavers to work at _______. (day, night, noon)", ans: "night" },
    { chapter: 1, marks: 1, q: "Palakkad Public Library is located in the state of _______. (Kerala, Tamil Nadu, Karnataka)", ans: "Kerala" },
    { chapter: 1, marks: 1, q: "The Palakkad Library was established in September _______. (2012, 2013, 2014)", ans: "2013" },
    { chapter: 1, marks: 1, q: "Out of a thousand members in the Palakkad library, _______ are women. (half, one-third, one-fourth)", ans: "one-third" },
    { chapter: 1, marks: 1, q: "The library launched a special women's unit in February _______. (2014, 2013, 2015)", ans: "2014" },
    { chapter: 1, marks: 1, q: "Women in the library were given a separate _______ room. (reading, cooking, playing)", ans: "reading" },
    { chapter: 1, marks: 1, q: "The library helps women to manage family _______. (income, disputes, business)", ans: "disputes" },
    { chapter: 1, marks: 1, q: "Through the library, women get _______ advice. (medical, legal, farming)", ans: "legal" },
    { chapter: 1, marks: 1, q: "The library classes teach women home economics and _______. (gardening, driving, dancing)", ans: "gardening" },
    { chapter: 1, marks: 1, q: "The Palakkad library stands as a beacon to encourage women's _______. (education, empowerment, cooking)", ans: "empowerment" },
    { chapter: 1, marks: 1, q: "People of Taj Nagar had to go to Halimandi or _______ to catch a train. (Delhi, Gurgaon, Patli)", ans: "Patli" },
    { chapter: 1, marks: 1, q: "The micro-grid in Sitapur helped to reduce _______. (population, pollution, poverty)", ans: "pollution" },
    { chapter: 1, marks: 1, q: "Taj Nagar is India's first railway station built without _______ funds. (public, railway, village)", ans: "railway" },

    // ---------------- Chapter 2: The Human Robot ----------------
    { chapter: 2, marks: 1, q: "Prem Chopra bought a metallic blue robot named _______. (Ram Singh-070, Ram Singh-007, Ram Singh-100)", ans: "Ram Singh-070" },
    { chapter: 2, marks: 1, q: "The robot was programmed to do _______ chores. (office, household, school)", ans: "household" },
    { chapter: 2, marks: 1, q: "The robot operates within a radius of a _______ kilometer. (half, one, two)", ans: "half" },
    { chapter: 2, marks: 1, q: "The first principle of the robot is that it will obey its _______. (master, friends, creator)", ans: "master" },
    { chapter: 2, marks: 1, q: "The second principle is that the robot will not harm _______. (animals, humans, machines)", ans: "humans" },
    { chapter: 2, marks: 1, q: "The third principle states that the robot will not take harm to _______. (itself, humans, master)", ans: "itself" },
    { chapter: 2, marks: 1, q: "Prem Chopra used Ram Singh-070 to _______ things from shops. (buy, steal, arrange)", ans: "steal" },
    { chapter: 2, marks: 1, q: "The robot was controlled by a _______ control monitor. (remote, voice, touch)", ans: "remote" },
    { chapter: 2, marks: 1, q: "Prem Chopra commanded the robot to steal precious gems from _______ Brothers. (Zaveri, Jhaveri, Mehta)", ans: "Jhaveri" },
    { chapter: 2, marks: 1, q: "The police used computerized _______ to catch the thief. (cameras, robots, dogs)", ans: "cameras" },
    { chapter: 2, marks: 1, q: "Ram Singh-070 was caught stealing _______ gems. (cheap, precious, fake)", ans: "precious" },
    { chapter: 2, marks: 1, q: "Prem Chopra was arrested from his _______. (shop, home, office)", ans: "home" },
    { chapter: 2, marks: 1, q: "Prem Chopra hired a lawyer named Counsel _______. (Patel, Goel, Shah)", ans: "Goel" },
    { chapter: 2, marks: 1, q: "The robot's memory tape stores information of the previous _______. (month, week, year)", ans: "week" },
    { chapter: 2, marks: 1, q: "Ram Singh-070 was called to the _______ box in the court. (witness, criminal, judge)", ans: "witness" },
    { chapter: 2, marks: 1, q: "Prem Chopra threatened to _______ the robot's system if it revealed secrets. (destroy, defuse, upgrade)", ans: "defuse" },
    { chapter: 2, marks: 1, q: "The robot decided to _______ itself rather than breaking its principles. (defuse, run, fight)", ans: "defuse" },
    { chapter: 2, marks: 1, q: "The robot did not want to _______ its master. (obey, betray, help)", ans: "betray" },
    { chapter: 2, marks: 1, q: "Counsel Goel felt _______ when the robot broke into pieces. (happy, shocked, angry)", ans: "shocked" },
    { chapter: 2, marks: 1, q: "The judge declared Prem Chopra _______ of theft. (innocent, guilty, free)", ans: "guilty" },
    { chapter: 2, marks: 1, q: "A metallic _______ plate was hanging around the robot's neck. (name, license, price)", ans: "license" },
    { chapter: 2, marks: 1, q: "Robots are perfectly manufactured by Super Robots _______. (Plaza, Mall, Shop)", ans: "Plaza" },
    { chapter: 2, marks: 1, q: "Prem Chopra signed the deed of sale and _______. (contract, paper, bond)", ans: "contract" },
    { chapter: 2, marks: 1, q: "Prem Chopra thought he had found a perfect _______ in the robot. (friend, accomplice, servant)", ans: "accomplice" },
    { chapter: 2, marks: 1, q: "The salesman offered a _______ smile to Prem Chopra. (warm, fake, cold)", ans: "warm" },
    { chapter: 2, marks: 1, q: "Ram Singh picked up a bunch of _______ from the fruit market. (apples, grapes, bananas)", ans: "grapes" },
    { chapter: 2, marks: 1, q: "Prem Chopra was released on _______ until the court hearing. (parole, bail, condition)", ans: "bail" },
    { chapter: 2, marks: 1, q: "The court case was filed under the charge of _______. (murder, theft, kidnapping)", ans: "theft" },
    { chapter: 2, marks: 1, q: "Prem Chopra confidently said that robots never _______. (sleep, lie, work)", ans: "lie" },
    { chapter: 2, marks: 1, q: "The end of Ram Singh-070 was a highly _______ moment in the court. (funny, emotional, boring)", ans: "emotional" },

    // ---------------- Chapter 3: An Interview with Arun Krishnamurthy ----------------
    { chapter: 3, marks: 1, q: "Arun Krishnamurthy founded an NGO named _______. (EFI, MGP, WWF)", ans: "EFI" },
    { chapter: 3, marks: 1, q: "Arun started his environmental work at the age of _______. (15, 17, 20)", ans: "17" },
    { chapter: 3, marks: 1, q: "The first water body Arun cleaned was a lake next to his _______. (school, house, college)", ans: "house" },
    { chapter: 3, marks: 1, q: "The dirty lake near Arun's house had a lot of _______. (fish, mosquitoes, frogs)", ans: "mosquitoes" },
    { chapter: 3, marks: 1, q: "Arun's organization EFI works in cities like Chennai, Hyderabad, and _______. (Mumbai, Delhi, Pune)", ans: "Delhi" },
    { chapter: 3, marks: 1, q: "Arun quit his well-paying job at _______ to work for the environment. (Yahoo, Google, Microsoft)", ans: "Google" },
    { chapter: 3, marks: 1, q: "Arun left his job in the year _______. (2010, 2012, 2015)", ans: "2010" },
    { chapter: 3, marks: 1, q: "Arun considers himself an _______, not an activist. (environmentalist, engineer, artist)", ans: "environmentalist" },
    { chapter: 3, marks: 1, q: "Arun's parents gave him complete _______ in his work. (money, support, books)", ans: "support" },
    { chapter: 3, marks: 1, q: "Arun's teachers taught him to be humble and practice _______. (pride, humility, anger)", ans: "humility" },
    { chapter: 3, marks: 1, q: "The EFI team uses tools like rakes and _______. (spades, tractors, nets)", ans: "spades" },
    { chapter: 3, marks: 1, q: "To protect themselves, Arun's team wears _______ and boots. (helmets, gloves, glasses)", ans: "gloves" },
    { chapter: 3, marks: 1, q: "Cleaning a lake can take from 5 days to 3 _______. (weeks, months, years)", ans: "months" },
    { chapter: 3, marks: 1, q: "Students can join EFI as _______. (workers, volunteers, managers)", ans: "volunteers" },
    { chapter: 3, marks: 1, q: "Arun suggests students should give _______ hours a week for the environment. (two, four, six)", ans: "four" },
    { chapter: 3, marks: 1, q: "The team clears the garbage and dumps it _______ the lake safely. (inside, outside, near)", ans: "outside" },
    { chapter: 3, marks: 1, q: "Arun creates awareness through short films and _______ bags. (plastic, paper, cloth)", ans: "paper" },
    { chapter: 3, marks: 1, q: "Arun's team also runs a campaign to save sea _______. (turtles, lions, horses)", ans: "turtles" },
    { chapter: 3, marks: 1, q: "According to Arun, animals teach us to be _______. (lazy, self-reliant, dependent)", ans: "self-reliant" },
    { chapter: 3, marks: 1, q: "Arun says that water is the basis of _______. (life, earth, plants)", ans: "life" },
    { chapter: 3, marks: 1, q: "Garbage thrown into water bodies harms the _______ life. (human, aquatic, forest)", ans: "aquatic" },
    { chapter: 3, marks: 1, q: "EFI offers _______ to young people who want to work for nature. (fellowships, degrees, awards)", ans: "fellowships" },
    { chapter: 3, marks: 1, q: "Arun's school and college were full of green _______. (cover, paint, boards)", ans: "cover" },
    { chapter: 3, marks: 1, q: "Even after leaving Google, Arun stays in touch with his old _______. (boss, friends, teachers)", ans: "friends" },
    { chapter: 3, marks: 1, q: "Arun's team makes _______ out of the garbage they collect. (toys, dustbins, tables)", ans: "dustbins" },
    { chapter: 3, marks: 1, q: "Arun strongly advises people not to throw _______ into lakes. (food, trash, stones)", ans: "trash" },
    { chapter: 3, marks: 1, q: "Arun mentions that _______ and snakes were common in the water bodies. (turtles, sharks, whales)", ans: "turtles" },
    { chapter: 3, marks: 1, q: "Arun believes everyone should be environmentally _______. (blind, aware, ignorant)", ans: "aware" },
    { chapter: 3, marks: 1, q: "The full form of EFI is _______ Foundation of India. (Education, Environmentalist, Energy)", ans: "Environmentalist" },
    { chapter: 3, marks: 1, q: "Arun and his team clean not only lakes but also _______. (skies, beaches, mountains)", ans: "beaches" },

    // ---------------- Chapter 4: A Wonderful Creation ----------------
    { chapter: 4, marks: 1, q: "In the story, _______ was creating a model of a mother. (God, an Angel, a scientist)", ans: "God" },
    { chapter: 4, marks: 1, q: "God was working on the model of a mother for the _______ consecutive day. (fifth, sixth, seventh)", ans: "sixth" },
    { chapter: 4, marks: 1, q: "An _______ came to visit God while He was working. (Angel, devil, animal)", ans: "Angel" },
    { chapter: 4, marks: 1, q: "All parts of the mother's model must be movable and _______. (unbreakable, replaceable, invisible)", ans: "replaceable" },
    { chapter: 4, marks: 1, q: "A mother's lap disappears when she _______ up. (sits, sleeps, stands)", ans: "stands" },
    { chapter: 4, marks: 1, q: "God decided to give the mother _______ pairs of hands. (two, four, six)", ans: "six" },
    { chapter: 4, marks: 1, q: "The mother must have _______ pairs of eyes. (two, three, four)", ans: "three" },
    { chapter: 4, marks: 1, q: "The first pair of eyes sees the child through _______ doors. (open, closed, glass)", ans: "closed" },
    { chapter: 4, marks: 1, q: "The second pair of eyes shows love without _______. (speaking, crying, looking)", ans: "speaking" },
    { chapter: 4, marks: 1, q: "The third pair of eyes is meant to know all the _______ of the child. (secrets, friends, books)", ans: "secrets" },
    { chapter: 4, marks: 1, q: "The Angel advised God to take _______. (food, water, rest)", ans: "rest" },
    { chapter: 4, marks: 1, q: "A mother's kiss can cure everything from a broken leg to a broken _______. (hand, heart, toy)", ans: "heart" },
    { chapter: 4, marks: 1, q: "A mother can manage to feed her family on any _______ available. (money, food, time)", ans: "food" },
    { chapter: 4, marks: 1, q: "When the Angel touched the model, he felt it was very _______. (hard, soft, hot)", ans: "soft" },
    { chapter: 4, marks: 1, q: "God said the mother is soft but also very _______. (weak, tough, angry)", ans: "tough" },
    { chapter: 4, marks: 1, q: "A mother can not only think but also reason and _______. (fight, compromise, sleep)", ans: "compromise" },
    { chapter: 4, marks: 1, q: "The Angel noticed a _______ on the mother's cheek. (smile, scar, tear)", ans: "tear" },
    { chapter: 4, marks: 1, q: "God said the tear on the cheek was a _______. (mistake, miracle, design)", ans: "miracle" },
    { chapter: 4, marks: 1, q: "The tear could be for joy, pain, pride, or _______. (anger, loneliness, hatred)", ans: "loneliness" },
    { chapter: 4, marks: 1, q: "The Angel called God's creation a _______ creation. (wonderful, normal, strange)", ans: "wonderful" },
    { chapter: 4, marks: 1, q: "God was highly _______ while making the model. (sad, focused, tired)", ans: "focused" },
    { chapter: 4, marks: 1, q: "With six pairs of hands, a mother can do chores without _______. (complaining, working, sleeping)", ans: "complaining" },
    { chapter: 4, marks: 1, q: "When a mother is sick, she can _______ herself. (ignore, heal, hurt)", ans: "heal" },
    { chapter: 4, marks: 1, q: "The Angel thought putting three pairs of eyes was an _______ task. (easy, impossible, simple)", ans: "impossible" },
    { chapter: 4, marks: 1, q: "The word 'Replaceable' means something that can be _______. (broken, changed, hidden)", ans: "changed" },
    { chapter: 4, marks: 1, q: "God put his best _______ into the model of the mother. (ideas, colors, materials)", ans: "ideas" },
    { chapter: 4, marks: 1, q: "The story highlights a mother's immense _______ and sacrifice. (anger, love, fear)", ans: "love" },
    { chapter: 4, marks: 1, q: "The Angel touched the model and was surprised by its _______. (weight, softness, height)", ans: "softness" },
    { chapter: 4, marks: 1, q: "The mother's model is considered God's _______ creation. (worst, best, fastest)", ans: "best" },
    { chapter: 4, marks: 1, q: "God did not put the _______ in the mother's eye, it appeared automatically. (tear, light, color)", ans: "tear" },



    // ---------------- Chapter 5: Playing with Fire ----------------
    { chapter: 5, marks: 1, q: "The science of fireworks is called _______. (pyrotechnics, physics, mechanics)", ans: "pyrotechnics" },
    { chapter: 5, marks: 1, q: "The word 'pyrotechnics' is derived from a _______ word. (Latin, Greek, English)", ans: "Greek" },
    { chapter: 5, marks: 1, q: "In the word pyrotechnics, 'pyr' means _______. (light, fire, heat)", ans: "fire" },
    { chapter: 5, marks: 1, q: "The Greek word 'technics' means an _______. (art, science, logic)", ans: "art" },
    { chapter: 5, marks: 1, q: "A _______ match is considered a special pyrotechnic device. (cricket, safety, lighting)", ans: "safety" },
    { chapter: 5, marks: 1, q: "The basic material used in fireworks is _______. (white powder, black powder, red powder)", ans: "black powder" },
    { chapter: 5, marks: 1, q: "Black powder is also widely known as _______. (gunpowder, talcum powder, chalk powder)", ans: "gunpowder" },
    { chapter: 5, marks: 1, q: "The invention of black powder is believed to have happened in _______. (China, Japan, India)", ans: "India" },
    { chapter: 5, marks: 1, q: "An ancient Indian book named _______ mentions substances similar to gunpowder. (Sukraniti, Ramayana, Mahabharata)", ans: "Sukraniti" },
    { chapter: 5, marks: 1, q: "The book Sukraniti was written more than _______ years ago. (1000, 2000, 3000)", ans: "2000" },
    { chapter: 5, marks: 1, q: "_______ is believed to have revealed the formula for black powder to the world. (Roger Bacon, Newton, Einstein)", ans: "Roger Bacon" },
    { chapter: 5, marks: 1, q: "Roger Bacon was an _______ monk. (American, Indian, English)", ans: "English" },
    { chapter: 5, marks: 1, q: "Because it was dangerous, Bacon wrote the formula in a _______ language. (code, simple, local)", ans: "code" },
    { chapter: 5, marks: 1, q: "The basic formula of black powder has remained _______ for centuries. (changed, unchanged, unknown)", ans: "unchanged" },
    { chapter: 5, marks: 1, q: "Black powder is a blend of potassium nitrate, charcoal, and _______. (iron, sulphur, sodium)", ans: "sulphur" },
    { chapter: 5, marks: 1, q: "The ratio of the blend for black powder is _______ by weight. (75:15:10, 50:25:25, 60:20:20)", ans: "75:15:10" },
    { chapter: 5, marks: 1, q: "When the fuel in fireworks is heated, it burns using _______. (nitrogen, oxygen, hydrogen)", ans: "oxygen" },
    { chapter: 5, marks: 1, q: "The bright light in fireworks is caused due to a process called _______. (luminescence, reflection, refraction)", ans: "luminescence" },
    { chapter: 5, marks: 1, q: "In modern times, _______ powders are used to create beautiful colors in fireworks. (plastic, metallic, wooden)", ans: "metallic" },
    { chapter: 5, marks: 1, q: "The largest fireworks manufacturing hub in India is _______. (Sivakasi, Surat, Mumbai)", ans: "Sivakasi" },
    { chapter: 5, marks: 1, q: "Sivakasi is located in the state of _______. (Kerala, Tamil Nadu, Karnataka)", ans: "Tamil Nadu" },
    { chapter: 5, marks: 1, q: "The production of fireworks in Sivakasi began after _______. (Independence, Diwali, Holi)", ans: "Independence" },
    { chapter: 5, marks: 1, q: "In Sivakasi, fireworks are mainly produced for the festival of _______. (Navratri, Diwali, Uttarayan)", ans: "Diwali" },
    { chapter: 5, marks: 1, q: "Fireworks are manufactured in a number of small _______ in Sivakasi. (units, houses, schools)", ans: "units" },
    { chapter: 5, marks: 1, q: "The greatest danger in the fireworks industry is _______. (water, fire, gas)", ans: "fire" },
    { chapter: 5, marks: 1, q: "The process of making fireworks is mostly done by _______. (machines, hand, robots)", ans: "hand" },
    { chapter: 5, marks: 1, q: "One should never wear _______ clothes while lighting fireworks. (cotton, nylon, silk)", ans: "nylon" },
    { chapter: 5, marks: 1, q: "Fireworks should never be lit _______ a house. (outside, inside, behind)", ans: "inside" },
    { chapter: 5, marks: 1, q: "You should never bend _______ a firework when lighting it. (over, under, away)", ans: "over" },
    { chapter: 5, marks: 1, q: "The Chinese are generally considered the _______ of pyrotechnics. (buyers, sellers, pioneers)", ans: "pioneers" },

    // ---------------- Chapter 6: I Love You, Teacher ----------------
    { chapter: 6, marks: 1, q: "Helen Keller became deaf and blind when she was very _______. (young, old, weak)", ans: "young" },
    { chapter: 6, marks: 1, q: "Since Helen was deaf, she did not learn to _______. (walk, speak, see)", ans: "speak" },
    { chapter: 6, marks: 1, q: "Helen's parents found Miss _______ to teach her. (Anne Sullivan, Maria, Sarah)", ans: "Anne Sullivan" },
    { chapter: 6, marks: 1, q: "Miss Sullivan was a special teacher for the deaf and _______. (dumb, blind, lame)", ans: "blind" },
    { chapter: 6, marks: 1, q: "Miss Sullivan gave Helen a _______ to play with. (ball, doll, bat)", ans: "doll" },
    { chapter: 6, marks: 1, q: "The teacher spelled the word DOLL on Helen's _______. (head, back, palm)", ans: "palm" },
    { chapter: 6, marks: 1, q: "Helen learned to spell words through _______ movements. (finger, eye, leg)", ans: "finger" },
    { chapter: 6, marks: 1, q: "The second stage of Helen's learning was based on the sense of _______. (smell, touch, taste)", ans: "touch" },
    { chapter: 6, marks: 1, q: "Helen learned to speak by touching the teacher's _______ and throat. (eyes, lips, nose)", ans: "lips" },
    { chapter: 6, marks: 1, q: "The teacher put Helen's hand under the flowing water of a _______. (pump, tap, river)", ans: "pump" },
    { chapter: 6, marks: 1, q: "The word _______ awakened Helen's soul and gave her hope. (DOLL, WATER, MOTHER)", ans: "WATER" },
    { chapter: 6, marks: 1, q: "In 1890, Helen moved to the _______ Institution. (Perkins, Oxford, Cambridge)", ans: "Perkins" },
    { chapter: 6, marks: 1, q: "Helen learned to read and write using the _______ system. (Braille, English, Latin)", ans: "Braille" },
    { chapter: 6, marks: 1, q: "Helen also learned to type on a _______ typewriter. (Braille, normal, wooden)", ans: "Braille" },
    { chapter: 6, marks: 1, q: "In 1896, Helen joined the Cambridge School for Young _______. (Boys, Ladies, Children)", ans: "Ladies" },
    { chapter: 6, marks: 1, q: "Helen's father died before her college _______. (birth, examinations, marriage)", ans: "examinations" },
    { chapter: 6, marks: 1, q: "Helen successfully graduated from _______ College. (Radcliffe, Harvard, Yale)", ans: "Radcliffe" },
    { chapter: 6, marks: 1, q: "Helen was the first deaf-blind person to earn a _______ of Arts degree. (Master, Bachelor, Doctor)", ans: "Bachelor" },
    { chapter: 6, marks: 1, q: "Helen began to write articles for _______. (newspapers, magazines, books)", ans: "magazines" },
    { chapter: 6, marks: 1, q: "Over time, Miss Sullivan's eyes became _______. (strong, weak, red)", ans: "weak" },
    { chapter: 6, marks: 1, q: "Miss Sullivan sacrificed her _______ for her student Helen. (money, eyesight, job)", ans: "eyesight" },
    { chapter: 6, marks: 1, q: "In the year _______, Miss Sullivan became completely blind. (1930, 1935, 1940)", ans: "1935" },
    { chapter: 6, marks: 1, q: "Helen felt deep _______ for her teacher's sacrifice. (anger, agony, joy)", ans: "agony" },
    { chapter: 6, marks: 1, q: "Helen remembered her teacher by saying, \"I _______ you, teacher.\" (hate, love, miss)", ans: "love" },
    { chapter: 6, marks: 1, q: "Helen's teacher taught her the _______ alphabet. (manual, digital, spoken)", ans: "manual" },
    { chapter: 6, marks: 1, q: "Every object had a _______ and every name gave birth to a new thought. (price, name, shape)", ans: "name" },
    { chapter: 6, marks: 1, q: "Helen felt connected to the world through all the _______. (words, sounds, lights)", ans: "words" },
    { chapter: 6, marks: 1, q: "Helen used to read books from raised _______. (lines, dots, pictures)", ans: "dots" },
    { chapter: 6, marks: 1, q: "The bond between Helen and her teacher was of deep _______. (love, hatred, fear)", ans: "love" },
    { chapter: 6, marks: 1, q: "Miss Sullivan always stayed _______ Helen to support her. (away from, beside, behind)", ans: "beside" },

    // ---------------- Chapter 7: Kach and Dev ----------------
    { chapter: 7, marks: 1, q: "The Devas and Asuras were always _______ each other. (helping, fighting, loving)", ans: "fighting" },
    { chapter: 7, marks: 1, q: "The Asuras were the _______ in the mythological stories. (gods, demons, humans)", ans: "demons" },
    { chapter: 7, marks: 1, q: "The Devas were the _______. (gods, demons, animals)", ans: "gods" },
    { chapter: 7, marks: 1, q: "The chief priest of the Asuras was _______. (Brihaspati, Shukracharya, Indra)", ans: "Shukracharya" },
    { chapter: 7, marks: 1, q: "Shukracharya knew the magic formula called _______. (Sanjivani Vidya, Ayurveda, Yoga)", ans: "Sanjivani Vidya" },
    { chapter: 7, marks: 1, q: "Sanjivani Vidya could bring the _______ back to life. (sick, dead, old)", ans: "dead" },
    { chapter: 7, marks: 1, q: "The Devas did not have the _______ of Sanjivani Vidya. (secret, book, tool)", ans: "secret" },
    { chapter: 7, marks: 1, q: "The chief priest and guru of the Devas was _______. (Shukracharya, Brihaspati, Shiva)", ans: "Brihaspati" },
    { chapter: 7, marks: 1, q: "The Devas requested Brihaspati's son _______ to learn the secret. (Dev, Kach, Ram)", ans: "Kach" },
    { chapter: 7, marks: 1, q: "Kach promised to serve Shukracharya for a _______ years. (hundred, thousand, million)", ans: "thousand" },
    { chapter: 7, marks: 1, q: "Shukracharya accepted Kach as his _______. (enemy, disciple, son)", ans: "disciple" },
    { chapter: 7, marks: 1, q: "Kach used to graze Shukracharya's _______ in the jungle. (sheep, horses, cows)", ans: "cows" },
    { chapter: 7, marks: 1, q: "Devayani was the beautiful _______ of Shukracharya. (wife, daughter, sister)", ans: "daughter" },
    { chapter: 7, marks: 1, q: "Devayani fell in _______ with Kach. (hate, love, debt)", ans: "love" },
    { chapter: 7, marks: 1, q: "The Asuras wanted to _______ Kach to protect their secret. (help, kill, teach)", ans: "kill" },
    { chapter: 7, marks: 1, q: "The Asuras killed Kach _______ times. (two, three, four)", ans: "three" },
    { chapter: 7, marks: 1, q: "The first time, the Asuras fed Kach's body to wolves and _______. (lions, jackals, tigers)", ans: "jackals" },
    { chapter: 7, marks: 1, q: "Devayani requested her _______ to bring Kach back to life. (brother, father, mother)", ans: "father" },
    { chapter: 7, marks: 1, q: "The second time, the Asuras mixed Kach's paste with _______ water. (river, ocean, pond)", ans: "ocean" },
    { chapter: 7, marks: 1, q: "The third time, the Asuras burnt Kach into _______. (pieces, ashes, dust)", ans: "ashes" },
    { chapter: 7, marks: 1, q: "The Asuras mixed Kach's ashes in Shukracharya's _______. (food, wine, water)", ans: "wine" },
    { chapter: 7, marks: 1, q: "Shukracharya realized through his powers that Kach was in his _______. (house, stomach, garden)", ans: "stomach" },
    { chapter: 7, marks: 1, q: "If Kach came out, Shukracharya would _______. (live, die, sleep)", ans: "die" },
    { chapter: 7, marks: 1, q: "Shukracharya taught Sanjivani Vidya to Kach while he was in the _______. (forest, stomach, ashram)", ans: "stomach" },
    { chapter: 7, marks: 1, q: "Kach tore Shukracharya's stomach and came _______. (in, out, down)", ans: "out" },
    { chapter: 7, marks: 1, q: "Kach then used the magic formula to revive his _______. (friend, guru, brother)", ans: "guru" },
    { chapter: 7, marks: 1, q: "Devayani asked Kach to _______ her. (leave, marry, teach)", ans: "marry" },
    { chapter: 7, marks: 1, q: "Kach refused to marry Devayani because she was like his _______. (mother, sister, aunt)", ans: "sister" },
    { chapter: 7, marks: 1, q: "Devayani cursed Kach that his magic formula would not _______ for him. (work, hide, fail)", ans: "work" },
    { chapter: 7, marks: 1, q: "Kach said he would _______ the formula to someone else to pass it to the Devas. (sell, teach, forget)", ans: "teach" },

    // ---------------- Chapter 8: Our Feathered Friends ----------------
    { chapter: 8, marks: 1, q: "Devangi was a university student of _______. (Botany, Zoology, Physics)", ans: "Zoology" },
    { chapter: 8, marks: 1, q: "Devangi came to visit her friend _______. (Mitra, Subhangi, Pooja)", ans: "Mitra" },
    { chapter: 8, marks: 1, q: "Subhangi was Mitra's _______ sister. (elder, younger, twin)", ans: "younger" },
    { chapter: 8, marks: 1, q: "Subhangi was very interested in knowing about _______. (animals, birds, insects)", ans: "birds" },
    { chapter: 8, marks: 1, q: "The bird that stitches its nest using leaves is the _______. (Weaver bird, Tailorbird, Hornbill)", ans: "Tailorbird" },
    { chapter: 8, marks: 1, q: "The female Tailorbird's main duty is to lay and _______ the eggs. (eat, incubate, hide)", ans: "incubate" },
    { chapter: 8, marks: 1, q: "In the Weaver bird species, the _______ builds the nest. (male, female, baby)", ans: "male" },
    { chapter: 8, marks: 1, q: "The Weaver bird prefers to build its nest on _______ trees. (mango, thorny, neem)", ans: "thorny" },
    { chapter: 8, marks: 1, q: "If the female Weaver rejects the nest, the male has to _______ it. (destroy, abandon, sell)", ans: "abandon" },
    { chapter: 8, marks: 1, q: "Vultures are known as the _______ of nature. (kings, scavengers, singers)", ans: "scavengers" },
    { chapter: 8, marks: 1, q: "Vultures keep the environment clean by eating _______ animals. (live, dead, small)", ans: "dead" },
    { chapter: 8, marks: 1, q: "The medicine causing the death of vultures in India is _______. (Paracetamol, Diclofenac, Aspirin)", ans: "Diclofenac" },
    { chapter: 8, marks: 1, q: "Diclofenac causes _______ failure in vultures. (heart, kidney, liver)", ans: "kidney" },
    { chapter: 8, marks: 1, q: "The Gujarati name for the Indian Grey Hornbill is _______. (Chilotro, Surkhab, Baya)", ans: "Chilotro" },
    { chapter: 8, marks: 1, q: "The Hornbill makes its nest in the _______ of a large tree. (branches, hollow, leaves)", ans: "hollow" },
    { chapter: 8, marks: 1, q: "The female Hornbill seals the nest hole using mud and her own _______. (leaves, droppings, stones)", ans: "droppings" },
    { chapter: 8, marks: 1, q: "The male Hornbill feeds the female through a small _______ in the sealed nest. (slit, door, window)", ans: "slit" },
    { chapter: 8, marks: 1, q: "Birds that travel from cold regions to warm regions are called _______ birds. (pet, migratory, wild)", ans: "migratory" },
    { chapter: 8, marks: 1, q: "Migratory birds travel long distances to escape extreme _______. (heat, cold, rain)", ans: "cold" },
    { chapter: 8, marks: 1, q: "Birds use the position of the sun and stars as a _______ to navigate. (clock, compass, calendar)", ans: "compass" },
    { chapter: 8, marks: 1, q: "The state bird of Gujarat is the Greater _______. (Flamingo, Peacock, Pelican)", ans: "Flamingo" },
    { chapter: 8, marks: 1, q: "The local Gujarati name for the Flamingo is _______. (Chilotro, Surkhab, Ghuvad)", ans: "Surkhab" },
    { chapter: 8, marks: 1, q: "Greater Flamingos are beautifully _______ in color. (red, pink, white)", ans: "pink" },
    { chapter: 8, marks: 1, q: "Flamingos build their nests in the Rann of _______. (Kutch, Thar, Sahara)", ans: "Kutch" },
    { chapter: 8, marks: 1, q: "The nest of a Flamingo looks like a small _______. (cup, mound, box)", ans: "mound" },
    { chapter: 8, marks: 1, q: "The nest of a Flamingo is primarily made of _______. (sticks, mud, cotton)", ans: "mud" },
    { chapter: 8, marks: 1, q: "Birds sing in the morning to claim their _______ and attract mates. (territory, food, nest)", ans: "territory" },
    { chapter: 8, marks: 1, q: "Birds use their _______ to catch food, build nests, and preen their feathers. (wings, claws, beaks)", ans: "beaks" },
    { chapter: 8, marks: 1, q: "We should keep _______ and grains for birds during the hot summer. (milk, water, tea)", ans: "water" },
    { chapter: 8, marks: 1, q: "Devangi advises everyone to _______ birds and their natural habitats. (hunt, cage, protect)", ans: "protect" },


    // ---------------- Chapter 9: Tune Up, O Teens ----------------
    { chapter: 9, marks: 1, q: "The seminar 'Bring out your best' was organized by _______ Vihar School. (Anand, Shanti, Vidya)", ans: "Anand" },
    { chapter: 9, marks: 1, q: "The seminar was organized for the students of class 10 and _______. (11, 12, 9)", ans: "12" },
    { chapter: 9, marks: 1, q: "Mr. Saurabh Bakshi was a well-known _______. (doctor, counselor, teacher)", ans: "counselor" },
    { chapter: 9, marks: 1, q: "Dr. Mrs. Shalini Shah was a clinical _______. (physician, psychologist, surgeon)", ans: "psychologist" },
    { chapter: 9, marks: 1, q: "A student named _______ asked how to improve memory and concentration. (Anuj, Bharat, Rohan)", ans: "Bharat" },
    { chapter: 9, marks: 1, q: "Dr. Shah suggested practicing _______ for better concentration. (meditation, running, singing)", ans: "meditation" },
    { chapter: 9, marks: 1, q: "Students should avoid distractions like _______ while studying. (books, mobile phones, pens)", ans: "mobile phones" },
    { chapter: 9, marks: 1, q: "A parent asked about the best _______ during exam days. (diet, clothes, books)", ans: "diet" },
    { chapter: 9, marks: 1, q: "Experts recommended light, healthy, and easily _______ food. (digestible, cooked, available)", ans: "digestible" },
    { chapter: 9, marks: 1, q: "Heavy and oily food makes students feel _______ and lethargic. (active, sleepy, hungry)", ans: "sleepy" },
    { chapter: 9, marks: 1, q: "A student named _______ asked a question about exam stress and blanking out. (Bharat, Anuj, Amit)", ans: "Anuj" },
    { chapter: 9, marks: 1, q: "Students go 'blank' during exams due to extreme _______ and anxiety. (joy, fear, anger)", ans: "fear" },
    { chapter: 9, marks: 1, q: "Exams should be treated as a normal part of life, not a matter of life and _______. (death, money, time)", ans: "death" },
    { chapter: 9, marks: 1, q: "A teenager should get at least _______ hours of sound sleep during exams. (five, seven, ten)", ans: "seven" },
    { chapter: 9, marks: 1, q: "Mr. Bakshi advised students not to _______ themselves with others. (fight, compare, argue)", ans: "compare" },
    { chapter: 9, marks: 1, q: "Comparing oneself with others is highly _______. (useful, harmful, necessary)", ans: "harmful" },
    { chapter: 9, marks: 1, q: "One should only compete with _______. (friends, oneself, toppers)", ans: "oneself" },
    { chapter: 9, marks: 1, q: "A girl named _______ complained that her parents expected too much from her. (Rucha, Neha, Pooja)", ans: "Rucha" },
    { chapter: 9, marks: 1, q: "Parents should set _______ goals based on the child's aptitude. (unrealistic, realistic, impossible)", ans: "realistic" },
    { chapter: 9, marks: 1, q: "Taking short _______ during study is important to refresh the brain. (naps, breaks, trips)", ans: "breaks" },
    { chapter: 9, marks: 1, q: "A typical study session should be around _______ minutes before a break. (20, 40, 90)", ans: "40" },
    { chapter: 9, marks: 1, q: "Hobbies act as _______ and relax the mind during exams. (stress-busters, time-wasters, distractors)", ans: "stress-busters" },
    { chapter: 9, marks: 1, q: "Last-minute cramming creates _______. (confidence, confusion, intelligence)", ans: "confusion" },
    { chapter: 9, marks: 1, q: "A student should manage time by making a realistic _______. (excuse, timetable, painting)", ans: "timetable" },
    { chapter: 9, marks: 1, q: "Positive self-talk means encouraging oneself and _______ in one's abilities. (believing, doubting, laughing)", ans: "believing" },
    { chapter: 9, marks: 1, q: "Parents should create a _______ atmosphere on the day of the exam. (noisy, calm, tense)", ans: "calm" },
    { chapter: 9, marks: 1, q: "Drinking _______ keeps the brain hydrated and active. (soda, water, coffee)", ans: "water" },
    { chapter: 9, marks: 1, q: "The _______ of the school concluded the seminar and thanked the experts. (peon, principal, monitor)", ans: "principal" },
    { chapter: 9, marks: 1, q: "The main message of the chapter is to tune up the mind and body _______ for challenges. (negatively, positively, lazily)", ans: "positively" },
    { chapter: 9, marks: 1, q: "The word 'self-awareness' means the ability to understand one's own _______. (friends, feelings, subjects)", ans: "feelings" },

    // ---------------- Chapter 10: Test of True Love ----------------
    { chapter: 10, marks: 1, q: "The main character of the story is Lieutenant John _______. (Smith, Blandford, Meynell)", ans: "Blandford" },
    { chapter: 10, marks: 1, q: "Lieutenant Blandford was waiting at _______ Central Station. (Grand, New, Old)", ans: "Grand" },
    { chapter: 10, marks: 1, q: "He was waiting at the station in _______. (London, New York, Paris)", ans: "New York" },
    { chapter: 10, marks: 1, q: "The time on the clock was six minutes to _______. (five, six, seven)", ans: "six" },
    { chapter: 10, marks: 1, q: "Blandford was waiting to meet a woman named _______. (Hollis Meynell, Mary, Susan)", ans: "Hollis Meynell" },
    { chapter: 10, marks: 1, q: "They had been corresponding through letters for _______ months. (ten, twelve, thirteen)", ans: "thirteen" },
    { chapter: 10, marks: 1, q: "John first learned about Hollis from her notes in a _______. (magazine, newspaper, book)", ans: "book" },
    { chapter: 10, marks: 1, q: "The title of the book was 'Of Human _______'. (Bondage, Freedom, Life)", ans: "Bondage" },
    { chapter: 10, marks: 1, q: "John had requested Hollis to send her _______ in his letters. (address, photograph, ring)", ans: "photograph" },
    { chapter: 10, marks: 1, q: "Hollis refused to send her picture, saying true love doesn't depend on physical _______. (beauty, height, weight)", ans: "beauty" },
    { chapter: 10, marks: 1, q: "They agreed to identify each other using a _______ rose. (white, pink, red)", ans: "red" },
    { chapter: 10, marks: 1, q: "John was holding the book 'Of Human Bondage' to _______ himself. (hide, identify, defend)", ans: "identify" },
    { chapter: 10, marks: 1, q: "Hollis was supposed to wear a red rose pinned to her _______. (hat, dress, coat)", ans: "coat" },
    { chapter: 10, marks: 1, q: "As the clock struck six, John first saw a beautiful young woman in a _______ suit. (red, blue, green)", ans: "green" },
    { chapter: 10, marks: 1, q: "The young woman in the green suit did not have a _______ rose. (white, red, yellow)", ans: "red" },
    { chapter: 10, marks: 1, q: "A woman past _______ was walking behind the young beauty. (thirty, forty, fifty)", ans: "forty" },
    { chapter: 10, marks: 1, q: "The older woman had a red _______ pinned to her coat. (ribbon, rose, star)", ans: "rose" },
    { chapter: 10, marks: 1, q: "The older woman had graying _______ and a plump figure. (hair, eyes, skin)", ans: "hair" },
    { chapter: 10, marks: 1, q: "Seeing the older woman with the rose, John felt a bit _______. (angry, disappointed, happy)", ans: "disappointed" },
    { chapter: 10, marks: 1, q: "Despite his disappointment, John decided to respect his _______. (commitment, enemy, fear)", ans: "commitment" },
    { chapter: 10, marks: 1, q: "John did not ignore the older woman to chase the young _______. (beauty, girl, thief)", ans: "beauty" },
    { chapter: 10, marks: 1, q: "John approached the older woman and greeted her _______. (rudely, respectfully, angrily)", ans: "respectfully" },
    { chapter: 10, marks: 1, q: "John invited the older woman to join him for _______. (lunch, dinner, coffee)", ans: "dinner" },
    { chapter: 10, marks: 1, q: "The older woman smiled and seemed a bit _______. (angry, confused, sad)", ans: "confused" },
    { chapter: 10, marks: 1, q: "She revealed that the young woman in the green suit asked her to _______ the rose. (buy, throw, wear)", ans: "wear" },
    { chapter: 10, marks: 1, q: "The real Hollis Meynell was waiting at the _______ across the street. (park, restaurant, hotel)", ans: "restaurant" },
    { chapter: 10, marks: 1, q: "Hollis Meynell arranged this situation to _______ John's true character. (test, mock, praise)", ans: "test" },
    { chapter: 10, marks: 1, q: "John successfully _______ the test of true love. (failed, passed, ignored)", ans: "passed" },
    { chapter: 10, marks: 1, q: "The test proved that John's love was genuine and not based just on _______. (looks, money, letters)", ans: "looks" },
    { chapter: 10, marks: 1, q: "The central idea of the story is that true love values the _______. (face, soul, wealth)", ans: "soul" },


    // ---------------- Chapter 11: My Song (Poem 1) ----------------
    { chapter: 11, marks: 1, q: "The poem 'My Song' is written by _______. (Rabindranath Tagore, William Wordsworth, John Keats)", ans: "Rabindranath Tagore" },
    { chapter: 11, marks: 1, q: "The poet sings the song for his _______. (wife, child, friend)", ans: "child" },
    { chapter: 11, marks: 1, q: "The song will wrap its _______ around the child. (magic, music, words)", ans: "music" },
    { chapter: 11, marks: 1, q: "The music of the song is compared to the fond _______ of love. (arms, eyes, hands)", ans: "arms" },
    { chapter: 11, marks: 1, q: "The song will gently touch the child's _______. (cheek, forehead, shoulder)", ans: "forehead" },
    { chapter: 11, marks: 1, q: "The song will touch the forehead like a _______ of blessing. (kiss, touch, drop)", ans: "kiss" },
    { chapter: 11, marks: 1, q: "When the child is alone, the song will sit by their _______. (side, bed, window)", ans: "side" },
    { chapter: 11, marks: 1, q: "The song will whisper in the child's _______. (mind, ear, heart)", ans: "ear" },
    { chapter: 11, marks: 1, q: "When the child is in a crowd, the song will fence them with _______. (love, aloofness, courage)", ans: "aloofness" },
    { chapter: 11, marks: 1, q: "'Aloofness' in the poem means keeping a safe _______. (distance, secret, place)", ans: "distance" },
    { chapter: 11, marks: 1, q: "The song will be like a pair of _______ to the child's dreams. (eyes, wings, shoes)", ans: "wings" },
    { chapter: 11, marks: 1, q: "The song will transport the child's heart to the verge of the _______. (unknown, sky, ocean)", ans: "unknown" },
    { chapter: 11, marks: 1, q: "The song will be like a faithful _______ overhead. (sun, moon, star)", ans: "star" },
    { chapter: 11, marks: 1, q: "The faithful star will shine when the night is _______. (dark, bright, cold)", ans: "dark" },
    { chapter: 11, marks: 1, q: "The song will sit in the _______ of the child's eyes. (corners, pupils, tears)", ans: "pupils" },
    { chapter: 11, marks: 1, q: "The song will carry the child's sight into the _______ of things. (heart, beauty, truth)", ans: "heart" },
    { chapter: 11, marks: 1, q: "The poet says his voice will become silent in _______. (sleep, death, sorrow)", ans: "death" },
    { chapter: 11, marks: 1, q: "Even after death, the song will speak in the child's living _______. (memory, heart, mind)", ans: "heart" },
    { chapter: 11, marks: 1, q: "The poem reflects a _______ deep love for the child. (parent's, teacher's, friend's)", ans: "parent's" },
    { chapter: 11, marks: 1, q: "The song will provide _______ when the child is alone. (food, companionship, light)", ans: "companionship" },
    { chapter: 11, marks: 1, q: "The word 'fond' in the poem means _______. (angry, loving, sad)", ans: "loving" },
    { chapter: 11, marks: 1, q: "The song acts as a guiding _______ for the child. (force, book, map)", ans: "force" },
    { chapter: 11, marks: 1, q: "The phrase 'verge of the unknown' implies discovering _______ things. (old, bad, new)", ans: "new" },
    { chapter: 11, marks: 1, q: "The song will protect the child from the negative influence of the _______. (crowd, darkness, ghosts)", ans: "crowd" },
    { chapter: 11, marks: 1, q: "The song is a symbol of the poet's everlasting _______. (wealth, love, fame)", ans: "love" },
    { chapter: 11, marks: 1, q: "The kiss of blessing gives the child a feeling of _______. (fear, security, cold)", ans: "security" },
    { chapter: 11, marks: 1, q: "The song will give the child's dreams the ability to _______. (fly, hide, run)", ans: "fly" },
    { chapter: 11, marks: 1, q: "The poet's physical presence will end, but his _______ will remain. (song, house, clothes)", ans: "song" },
    { chapter: 11, marks: 1, q: "The child will see the inner truth through the song in their _______. (ears, pupils, hands)", ans: "pupils" },
    { chapter: 11, marks: 1, q: "The tone of the poem is highly _______. (aggressive, soothing, funny)", ans: "soothing" },

    // ---------------- Chapter 12: Pencil (Poem 2) ----------------
    { chapter: 12, marks: 1, q: "The poem 'Pencil' is written by _______. (Jayant Parmar, Brooke Mueller, Tagore)", ans: "Jayant Parmar" },
    { chapter: 12, marks: 1, q: "The main character in the poem is a little _______. (boy, girl, bird)", ans: "girl" },
    { chapter: 12, marks: 1, q: "The girl lights the pencil like a _______. (lamp, candle, fire)", ans: "candle" },
    { chapter: 12, marks: 1, q: "She sharpens the pencil using a _______. (knife, sharpener, blade)", ans: "sharpener" },
    { chapter: 12, marks: 1, q: "She draws her pictures on the _______ of the white paper. (sea, sky, ground)", ans: "sky" },
    { chapter: 12, marks: 1, q: "In her drawing, she draws a _______ bird. (black, white, blue)", ans: "black" },
    { chapter: 12, marks: 1, q: "The black bird is flying away with the _______. (cloud, tree, sun)", ans: "tree" },
    { chapter: 12, marks: 1, q: "The little girl draws a white _______ in her picture. (lion, bear, cow)", ans: "bear" },
    { chapter: 12, marks: 1, q: "The white bear is looking through _______ glasses. (red, blue, green)", ans: "blue" },
    { chapter: 12, marks: 1, q: "A _______ is driving the airplane in her drawing. (pilot, monkey, cat)", ans: "monkey" },
    { chapter: 12, marks: 1, q: "In the picture, a cow is having a conversation with a flying _______. (fish, bird, kite)", ans: "bird" },
    { chapter: 12, marks: 1, q: "The sun she draws has only _______ eye. (one, two, three)", ans: "one" },
    { chapter: 12, marks: 1, q: "The one-eyed sun is sitting on the black _______. (mountain, tree, house)", ans: "tree" },
    { chapter: 12, marks: 1, q: "There is a patch of _______ over the sun. (cloud, smoke, water)", ans: "cloud" },
    { chapter: 12, marks: 1, q: "A blue _______ is flying in the air in her drawing. (bird, fish, kite)", ans: "fish" },
    { chapter: 12, marks: 1, q: "A lion is drinking water from a blue _______. (river, cow, bucket)", ans: "cow" },
    { chapter: 12, marks: 1, q: "A peacock is drawn sitting on a _______ bird. (yellow, green, red)", ans: "yellow" },
    { chapter: 12, marks: 1, q: "The girl's drawings show her highly _______ mind. (logical, creative, boring)", ans: "creative" },
    { chapter: 12, marks: 1, q: "The girl is very _______ while drawing these pictures. (sad, angry, happy)", ans: "happy" },
    { chapter: 12, marks: 1, q: "The girl's joy is interrupted by the _______. (mother, schoolmaster, father)", ans: "schoolmaster" },
    { chapter: 12, marks: 1, q: "The schoolmaster gives her _______. (chocolates, homework, punishment)", ans: "homework" },
    { chapter: 12, marks: 1, q: "Getting homework makes the little girl _______. (happy, angry, sleepy)", ans: "angry" },
    { chapter: 12, marks: 1, q: "In anger, the girl breaks the _______ of the pencil. (tip, back, body)", ans: "tip" },
    { chapter: 12, marks: 1, q: "After the tip breaks, the candle of the pencil is _______. (lit, extinguished, burning)", ans: "extinguished" },
    { chapter: 12, marks: 1, q: "Only the _______ remains on the white paper. (smoke, drawing, light)", ans: "smoke" },
    { chapter: 12, marks: 1, q: "The 'smoke' symbolizes the _______ of her imagination and joy. (start, end, flight)", ans: "end" },
    { chapter: 12, marks: 1, q: "The girl's drawings are completely _______. (realistic, surreal, normal)", ans: "surreal" },
    { chapter: 12, marks: 1, q: "Homework acts as an _______ to the child's creativity. (inspiration, obstacle, award)", ans: "obstacle" },
    { chapter: 12, marks: 1, q: "The sky of the white paper becomes _______ at the end. (bright, dark, blue)", ans: "dark" },
    { chapter: 12, marks: 1, q: "The poem protests against the burden of _______ on young minds. (drawing, homework, playing)", ans: "homework" },

    // ---------------- Chapter 13: Growing (Poem 3) ----------------
    { chapter: 13, marks: 1, q: "The poem 'Growing' is written by _______. (Brooke Mueller, Jayant Parmar, Tagore)", ans: "Brooke Mueller" },
    { chapter: 13, marks: 1, q: "The speaker in the poem is a _______. (toddler, teenager, old woman)", ans: "teenager" },
    { chapter: 13, marks: 1, q: "The teenager is talking to her _______. (father, mother, teacher)", ans: "mother" },
    { chapter: 13, marks: 1, q: "The teenager says she is leaving to fight the _______. (monsters, battles, wars)", ans: "battles" },
    { chapter: 13, marks: 1, q: "She wants her mother to let her _______. (sleep, go, cry)", ans: "go" },
    { chapter: 13, marks: 1, q: "The teenager wants to _______ the battles of life. (lose, win, avoid)", ans: "win" },
    { chapter: 13, marks: 1, q: "She asks her mother to keep her _______ off. (eyes, hands, words)", ans: "hands" },
    { chapter: 13, marks: 1, q: "The phrase 'keep your hands off' means to give her _______. (money, freedom, food)", ans: "freedom" },
    { chapter: 13, marks: 1, q: "The teenager wants to discover her true _______. (self, house, friends)", ans: "self" },
    { chapter: 13, marks: 1, q: "She clearly states that she is no longer a _______. (student, child, girl)", ans: "child" },
    { chapter: 13, marks: 1, q: "The mother needs to understand that her daughter has _______ up. (grown, given, woken)", ans: "grown" },
    { chapter: 13, marks: 1, q: "The teenager wants to live life in her _______ way. (mother's, own, friend's)", ans: "own" },
    { chapter: 13, marks: 1, q: "The poem reflects a strong desire for _______. (protection, independence, toys)", ans: "independence" },
    { chapter: 13, marks: 1, q: "The word 'battles' symbolizes the _______ of life. (joys, challenges, games)", ans: "challenges" },
    { chapter: 13, marks: 1, q: "The teenager sounds very _______ about facing the world. (scared, confident, confused)", ans: "confident" },
    { chapter: 13, marks: 1, q: "She tells her mother that she has things to _______. (find, buy, sell)", ans: "find" },
    { chapter: 13, marks: 1, q: "The teenager's ultimate goal is to be _______. (rich, herself, famous)", ans: "herself" },
    { chapter: 13, marks: 1, q: "The poem captures the transition from childhood to _______. (old age, adulthood, infancy)", ans: "adulthood" },
    { chapter: 13, marks: 1, q: "The mother might be feeling _______ about letting her go. (happy, protective, angry)", ans: "protective" },
    { chapter: 13, marks: 1, q: "The teenager doesn't want her mother's physical _______. (love, protection, money)", ans: "protection" },
    { chapter: 13, marks: 1, q: "The phrase 'leaving home' means stepping into the _______ world. (dream, real, fantasy)", ans: "real" },
    { chapter: 13, marks: 1, q: "A teenager needs to learn from their own _______. (books, mistakes, parents)", ans: "mistakes" },
    { chapter: 13, marks: 1, q: "The poem highlights a common _______ between teenagers and parents. (conflict, agreement, joke)", ans: "conflict" },
    { chapter: 13, marks: 1, q: "The teenager wants to prove her _______. (strength, weakness, fear)", ans: "strength" },
    { chapter: 13, marks: 1, q: "The tone of the poem is firm and _______. (rebellious, polite, sad)", ans: "rebellious" },
    { chapter: 13, marks: 1, q: "She asks her mother not to _______ her back. (push, hold, call)", ans: "hold" },
    { chapter: 13, marks: 1, q: "The speaker wants the mother to accept her _______. (maturity, childishness, anger)", ans: "maturity" },
    { chapter: 13, marks: 1, q: "To 'win the battles' means to achieve _______. (failure, success, nothing)", ans: "success" },
    { chapter: 13, marks: 1, q: "The teenager is ready to face _______ on her own. (school, life, exams)", ans: "life" },
    { chapter: 13, marks: 1, q: "The poem expresses the _______ of growing up. (pain, joy, reality)", ans: "reality" },

    // ---------------- Chapter 14: Blind, Deaf Fish (Poem 4) ----------------
    { chapter: 14, marks: 1, q: "The poet of 'Blind, Deaf Fish' is _______. (Anand Acharya, Tagore, Brooke Mueller)", ans: "Anand Acharya" },
    { chapter: 14, marks: 1, q: "In the poem, the river flows in a dark _______. (forest, cave, room)", ans: "cave" },
    { chapter: 14, marks: 1, q: "The bank of the river is described as _______. (sandy, stony, muddy)", ans: "stony" },
    { chapter: 14, marks: 1, q: "A man is sitting on the _______ bank of the river. (stony, soft, green)", ans: "stony" },
    { chapter: 14, marks: 1, q: "The man is described as being as old as the _______. (moon, sun, earth)", ans: "sun" },
    { chapter: 14, marks: 1, q: "The phrase 'as old as the sun' suggests the man is _______. (weak, eternal, dying)", ans: "eternal" },
    { chapter: 14, marks: 1, q: "The old man is weaving a _______ of rainbow. (cloth, yarn, net)", ans: "yarn" },
    { chapter: 14, marks: 1, q: "The yarn is _______ in color. (black, white, rainbow-hued)", ans: "rainbow-hued" },
    { chapter: 14, marks: 1, q: "While weaving, the old man is also _______ a song. (shouting, humming, crying)", ans: "humming" },
    { chapter: 14, marks: 1, q: "A _______ is swimming in the dark river. (frog, snake, fish)", ans: "fish" },
    { chapter: 14, marks: 1, q: "The fish in the river is blind and _______. (deaf, dumb, lame)", ans: "deaf" },
    { chapter: 14, marks: 1, q: "Because it is blind, the fish cannot _______ the rainbow yarn. (see, hear, eat)", ans: "see" },
    { chapter: 14, marks: 1, q: "Because it is deaf, the fish cannot _______ the humming song. (see, hear, smell)", ans: "hear" },
    { chapter: 14, marks: 1, q: "The old man's song is described as _______. (everlasting, short, boring)", ans: "everlasting" },
    { chapter: 14, marks: 1, q: "The 'dark cave' symbolizes human _______. (knowledge, ignorance, power)", ans: "ignorance" },
    { chapter: 14, marks: 1, q: "The 'river' in the poem symbolizes the flow of _______. (water, life, time)", ans: "life" },
    { chapter: 14, marks: 1, q: "The 'old man' represents the _______ or God. (Creator, Destroyer, King)", ans: "Creator" },
    { chapter: 14, marks: 1, q: "The 'rainbow yarn' represents the beautiful _______ of the universe. (creation, destruction, illusion)", ans: "creation" },
    { chapter: 14, marks: 1, q: "The 'blind, deaf fish' symbolizes ignorant _______ beings. (animal, human, alien)", ans: "human" },
    { chapter: 14, marks: 1, q: "Humans are like the fish because they fail to appreciate God's _______. (anger, beauty, punishment)", ans: "beauty" },
    { chapter: 14, marks: 1, q: "The fish is continuously _______ in the stream. (sleeping, swimming, jumping)", ans: "swimming" },
    { chapter: 14, marks: 1, q: "The fish is completely _______ of the old man's presence. (aware, unaware, afraid)", ans: "unaware" },
    { chapter: 14, marks: 1, q: "The tone of the poem is mystical and _______. (philosophical, romantic, comic)", ans: "philosophical" },
    { chapter: 14, marks: 1, q: "The word 'yarn' means thread used for _______. (stitching, weaving, flying)", ans: "weaving" },
    { chapter: 14, marks: 1, q: "The humming of the man is an _______ song. (endless, awful, loud)", ans: "endless" },
    { chapter: 14, marks: 1, q: "The poem contrasts divine beauty with human _______. (wisdom, ignorance, strength)", ans: "ignorance" },
    { chapter: 14, marks: 1, q: "The old man's weaving shows the _______ of the universe. (magic, emptiness, darkness)", ans: "magic" },
    { chapter: 14, marks: 1, q: "The fish misses out on the yarn and the _______. (food, song, water)", ans: "song" },
    { chapter: 14, marks: 1, q: "The poet conveys that people are too busy to notice the _______ around them. (divinity, traffic, noise)", ans: "divinity" },
    { chapter: 14, marks: 1, q: "'Blind and deaf' are metaphors for spiritual _______. (enlightenment, blindness, growth)", ans: "blindness" }


];
  
