var englishTrueFalseDB_Std10 = [

    // ---------------- Chapter 1: Against the Odds ----------------
    { chapter: 1, marks: 1, q: "Taj Nagar is located near Gurgaon.", ans: "True" },
    { chapter: 1, marks: 1, q: "The villagers of Taj Nagar wanted a bus station in their village.", ans: "False" },
    { chapter: 1, marks: 1, q: "The villagers collected 21 lakh rupees to build the railway station.", ans: "True" },
    { chapter: 1, marks: 1, q: "Most of the people living in Taj Nagar are businessmen.", ans: "False" },
    { chapter: 1, marks: 1, q: "The railway department refused to build the station citing a lack of funds.", ans: "True" },
    { chapter: 1, marks: 1, q: "The villagers formed an 11-member committee to build the station.", ans: "True" },
    { chapter: 1, marks: 1, q: "The Taj Nagar railway station started operating in 2012.", ans: "False" },
    { chapter: 1, marks: 1, q: "Sitapur district is located in the state of Uttar Pradesh.", ans: "True" },
    { chapter: 1, marks: 1, q: "Over 60% of households in Sitapur were without power.", ans: "True" },
    { chapter: 1, marks: 1, q: "MGP stands for Mera Gaon Power.", ans: "True" },
    { chapter: 1, marks: 1, q: "MGP provides solar power at a higher cost than kerosene.", ans: "False" },
    { chapter: 1, marks: 1, q: "Azaz was the first electrician of the MGP project in the village.", ans: "True" },
    { chapter: 1, marks: 1, q: "Solar panels in Sitapur were installed facing North.", ans: "False" },
    { chapter: 1, marks: 1, q: "Customers in Sitapur get two LEDs and a charging point for 25 rupees a week.", ans: "True" },
    { chapter: 1, marks: 1, q: "The Palakkad Public Library is situated in Kerala.", ans: "True" },
    { chapter: 1, marks: 1, q: "The Palakkad Library was established in September 2013.", ans: "True" },
    { chapter: 1, marks: 1, q: "Only 10% of the members of the Palakkad Library are women.", ans: "False" },
    { chapter: 1, marks: 1, q: "The library launched a special women's unit in February 2014.", ans: "True" },
    { chapter: 1, marks: 1, q: "The library does not provide a separate reading room for women.", ans: "False" },
    { chapter: 1, marks: 1, q: "Workshops in the library teach women about home economics and gardening.", ans: "True" },
    { chapter: 1, marks: 1, q: "The library helps women to resolve family disputes.", ans: "True" },
    { chapter: 1, marks: 1, q: "The Palakkad Library is considered a beacon for women empowerment.", ans: "True" },
    { chapter: 1, marks: 1, q: "Taj Nagar is India's first station built completely without railway funds.", ans: "True" },
    { chapter: 1, marks: 1, q: "Micro-grids in Sitapur increased pollution in the village.", ans: "False" },
    { chapter: 1, marks: 1, q: "The women's unit in Palakkad Library encourages women to waste their time.", ans: "False" },
    { chapter: 1, marks: 1, q: "Earlier, people of Taj Nagar had to go to Halimandi or Patli to catch a train.", ans: "True" },
    { chapter: 1, marks: 1, q: "The solar panels in Sitapur are installed on weak mud walls.", ans: "False" },
    { chapter: 1, marks: 1, q: "Solar light helps weavers to work comfortably at night.", ans: "True" },
    { chapter: 1, marks: 1, q: "Women get legal advice from the Palakkad Library.", ans: "True" },
    { chapter: 1, marks: 1, q: "The villagers of Taj Nagar struggled for 25 years to get a railway station.", ans: "True" },

    // ---------------- Chapter 2: The Human Robot ----------------
    { chapter: 2, marks: 1, q: "Prem Chopra bought a robot named Ram Singh-070.", ans: "True" },
    { chapter: 2, marks: 1, q: "The robot was metallic red in color.", ans: "False" },
    { chapter: 2, marks: 1, q: "The robot was programmed to do household chores.", ans: "True" },
    { chapter: 2, marks: 1, q: "The robot operates within a radius of 10 kilometers.", ans: "False" },
    { chapter: 2, marks: 1, q: "The first principle of the robot is that it will obey its master.", ans: "True" },
    { chapter: 2, marks: 1, q: "The second principle states that the robot will harm humans.", ans: "False" },
    { chapter: 2, marks: 1, q: "The third principle is that the robot will not let harm come to itself.", ans: "True" },
    { chapter: 2, marks: 1, q: "Prem Chopra used the robot to steal precious gems.", ans: "True" },
    { chapter: 2, marks: 1, q: "Ram Singh-070 was controlled by a remote control.", ans: "True" },
    { chapter: 2, marks: 1, q: "The robot was caught stealing from Jhaveri Brothers.", ans: "True" },
    { chapter: 2, marks: 1, q: "The police used dogs to catch the robot.", ans: "False" },
    { chapter: 2, marks: 1, q: "Prem Chopra was arrested from the market.", ans: "False" },
    { chapter: 2, marks: 1, q: "Prem Chopra hired Counsel Goel as his lawyer.", ans: "True" },
    { chapter: 2, marks: 1, q: "The robot's memory tape stores information for a whole month.", ans: "False" },
    { chapter: 2, marks: 1, q: "Ram Singh-070 was called to the witness box in the court.", ans: "True" },
    { chapter: 2, marks: 1, q: "Prem Chopra threatened to defuse the robot's system.", ans: "True" },
    { chapter: 2, marks: 1, q: "The robot betrayed its master in the court.", ans: "False" },
    { chapter: 2, marks: 1, q: "The robot decided to defuse itself to save its principles.", ans: "True" },
    { chapter: 2, marks: 1, q: "Counsel Goel was happy when the robot broke into pieces.", ans: "False" },
    { chapter: 2, marks: 1, q: "The judge declared Prem Chopra innocent.", ans: "False" },
    { chapter: 2, marks: 1, q: "A license plate was hanging around the robot's neck.", ans: "True" },
    { chapter: 2, marks: 1, q: "Prem Chopra never signed any deed of sale for the robot.", ans: "False" },
    { chapter: 2, marks: 1, q: "The salesman gave Prem Chopra a warm smile.", ans: "True" },
    { chapter: 2, marks: 1, q: "Ram Singh-070 was manufactured by Super Robots Plaza.", ans: "True" },
    { chapter: 2, marks: 1, q: "The robot picked up a bunch of apples from the fruit market.", ans: "False" },
    { chapter: 2, marks: 1, q: "Prem Chopra was released on bail before the court hearing.", ans: "True" },
    { chapter: 2, marks: 1, q: "The court case against Prem Chopra was filed under the charge of theft.", ans: "True" },
    { chapter: 2, marks: 1, q: "Prem Chopra firmly believed that robots never lie.", ans: "True" },
    { chapter: 2, marks: 1, q: "The robot spoke all the secrets of its master in the court.", ans: "False" },
    { chapter: 2, marks: 1, q: "The destruction of the robot was an emotional moment in the court.", ans: "True" },

    // ---------------- Chapter 3: An Interview with Arun Krishnamurthy ----------------
    { chapter: 3, marks: 1, q: "Arun Krishnamurthy founded an NGO named EFI.", ans: "True" },
    { chapter: 3, marks: 1, q: "EFI stands for Environmentalist Foundation of India.", ans: "True" },
    { chapter: 3, marks: 1, q: "Arun started his environmental work at the age of 25.", ans: "False" },
    { chapter: 3, marks: 1, q: "The first water body Arun cleaned was a lake near his house.", ans: "True" },
    { chapter: 3, marks: 1, q: "The dirty lake near Arun's house had a lot of mosquitoes.", ans: "True" },
    { chapter: 3, marks: 1, q: "Arun's organization only works in Chennai.", ans: "False" },
    { chapter: 3, marks: 1, q: "Arun quit a high-paying job at Google to protect the environment.", ans: "True" },
    { chapter: 3, marks: 1, q: "Arun left his job at Google in the year 2010.", ans: "True" },
    { chapter: 3, marks: 1, q: "Arun calls himself an environmental activist.", ans: "False" },
    { chapter: 3, marks: 1, q: "Arun's parents did not support his environmental work.", ans: "False" },
    { chapter: 3, marks: 1, q: "Arun's teachers taught him to practice humility.", ans: "True" },
    { chapter: 3, marks: 1, q: "The EFI team uses tools like rakes and spades.", ans: "True" },
    { chapter: 3, marks: 1, q: "Arun's team cleans lakes with bare hands without any safety gear.", ans: "False" },
    { chapter: 3, marks: 1, q: "Cleaning a lake can take anywhere from 5 days to 3 months.", ans: "True" },
    { chapter: 3, marks: 1, q: "Students can join the EFI organization as volunteers.", ans: "True" },
    { chapter: 3, marks: 1, q: "Arun suggests students should dedicate 10 hours a week for the environment.", ans: "False" },
    { chapter: 3, marks: 1, q: "Arun's team dumps the garbage outside the lake in a safe place.", ans: "True" },
    { chapter: 3, marks: 1, q: "Arun creates awareness by making short films and paper bags.", ans: "True" },
    { chapter: 3, marks: 1, q: "Arun's team runs campaigns to save sea turtles.", ans: "True" },
    { chapter: 3, marks: 1, q: "Arun believes that animals teach us to be dependent on others.", ans: "False" },
    { chapter: 3, marks: 1, q: "Arun considers water to be the basis of life.", ans: "True" },
    { chapter: 3, marks: 1, q: "Throwing garbage into water bodies is good for aquatic animals.", ans: "False" },
    { chapter: 3, marks: 1, q: "EFI offers fellowships to young people interested in the environment.", ans: "True" },
    { chapter: 3, marks: 1, q: "Arun's school and college had very little green cover.", ans: "False" },
    { chapter: 3, marks: 1, q: "Arun is still in touch with his old friends from Google.", ans: "True" },
    { chapter: 3, marks: 1, q: "Arun's team makes dustbins out of collected garbage.", ans: "True" },
    { chapter: 3, marks: 1, q: "Arun advises people not to throw trash into lakes.", ans: "True" },
    { chapter: 3, marks: 1, q: "Arun mentioned that turtles and snakes were often found in the lakes.", ans: "True" },
    { chapter: 3, marks: 1, q: "Arun thinks everyone should be environmentally aware.", ans: "True" },
    { chapter: 3, marks: 1, q: "Arun and his team also clean beaches along with lakes.", ans: "True" },

    // ---------------- Chapter 4: A Wonderful Creation ----------------
    { chapter: 4, marks: 1, q: "In the story, an Angel was creating a model of a mother.", ans: "False" },
    { chapter: 4, marks: 1, q: "God had been working on the model for six consecutive days.", ans: "True" },
    { chapter: 4, marks: 1, q: "God wanted all parts of the mother to be movable and replaceable.", ans: "True" },
    { chapter: 4, marks: 1, q: "A mother's lap disappears when she stands up.", ans: "True" },
    { chapter: 4, marks: 1, q: "God decided to give the mother four pairs of hands.", ans: "False" },
    { chapter: 4, marks: 1, q: "The mother must have three pairs of eyes.", ans: "True" },
    { chapter: 4, marks: 1, q: "The first pair of eyes sees the child through closed doors.", ans: "True" },
    { chapter: 4, marks: 1, q: "The second pair of eyes is used to scold the child.", ans: "False" },
    { chapter: 4, marks: 1, q: "The third pair of eyes is meant to know all the child's secrets.", ans: "True" },
    { chapter: 4, marks: 1, q: "The Angel advised God to take rest.", ans: "True" },
    { chapter: 4, marks: 1, q: "A mother's kiss can cure a broken leg and a broken heart.", ans: "True" },
    { chapter: 4, marks: 1, q: "A mother requires very expensive food to survive.", ans: "False" },
    { chapter: 4, marks: 1, q: "When the Angel touched the model, he found it to be very hard.", ans: "False" },
    { chapter: 4, marks: 1, q: "God said that a mother is soft but also very tough.", ans: "True" },
    { chapter: 4, marks: 1, q: "A mother can think, reason, and compromise.", ans: "True" },
    { chapter: 4, marks: 1, q: "The Angel noticed a smile on the mother's cheek.", ans: "False" },
    { chapter: 4, marks: 1, q: "God said that He deliberately put the tear on the mother's cheek.", ans: "False" },
    { chapter: 4, marks: 1, q: "The tear on the cheek was considered a miracle.", ans: "True" },
    { chapter: 4, marks: 1, q: "The tear could be for joy, pain, pride, or loneliness.", ans: "True" },
    { chapter: 4, marks: 1, q: "The Angel called the creation of the mother a wonderful creation.", ans: "True" },
    { chapter: 4, marks: 1, q: "God was highly distracted while making the mother's model.", ans: "False" },
    { chapter: 4, marks: 1, q: "With six pairs of hands, a mother can manage her family without complaining.", ans: "True" },
    { chapter: 4, marks: 1, q: "When a mother is sick, she cannot heal herself.", ans: "False" },
    { chapter: 4, marks: 1, q: "The Angel thought that putting three pairs of eyes was an easy task.", ans: "False" },
    { chapter: 4, marks: 1, q: "The word 'Replaceable' means something that cannot be changed.", ans: "False" },
    { chapter: 4, marks: 1, q: "God put His best ideas into the model of the mother.", ans: "True" },
    { chapter: 4, marks: 1, q: "The story highlights a mother's immense love and sacrifice.", ans: "True" },
    { chapter: 4, marks: 1, q: "A mother can feed her family on whatever food is available.", ans: "True" },
    { chapter: 4, marks: 1, q: "God created the mother's model in just one hour.", ans: "False" },
    { chapter: 4, marks: 1, q: "The mother is considered God's best creation in the story.", ans: "True" },

    var englishTrueFalseDB_Std10_Part2 = [

    // ---------------- Chapter 5: Playing with Fire ----------------
    { chapter: 5, marks: 1, q: "Pyrotechnics includes only fireworks.", ans: "False" },
    { chapter: 5, marks: 1, q: "The word 'pyrotechnics' is derived from a Latin word.", ans: "False" },
    { chapter: 5, marks: 1, q: "'Pyr' means fire in the Greek language.", ans: "True" },
    { chapter: 5, marks: 1, q: "A safety match is considered a special pyrotechnic device.", ans: "True" },
    { chapter: 5, marks: 1, q: "Black powder is also widely known as gunpowder.", ans: "True" },
    { chapter: 5, marks: 1, q: "Black powder was invented in China.", ans: "False" },
    { chapter: 5, marks: 1, q: "The ancient Indian text Sukraniti mentions substances similar to gunpowder.", ans: "True" },
    { chapter: 5, marks: 1, q: "Sukraniti was written around 500 years ago.", ans: "False" },
    { chapter: 5, marks: 1, q: "Roger Bacon was an English monk.", ans: "True" },
    { chapter: 5, marks: 1, q: "Roger Bacon wrote the formula for black powder in a code language because it was dangerous.", ans: "True" },
    { chapter: 5, marks: 1, q: "The basic formula of black powder has changed many times over the centuries.", ans: "False" },
    { chapter: 5, marks: 1, q: "Black powder is a blend of potassium nitrate, charcoal, and sulphur.", ans: "True" },
    { chapter: 5, marks: 1, q: "The ratio of the blend for black powder is 75:15:10 by weight.", ans: "True" },
    { chapter: 5, marks: 1, q: "The bright light in fireworks is caused by a process called luminescence.", ans: "True" },
    { chapter: 5, marks: 1, q: "Metallic powders are used to add beautiful colors to fireworks.", ans: "True" },
    { chapter: 5, marks: 1, q: "Sivakasi is the largest fireworks manufacturing hub in India.", ans: "True" },
    { chapter: 5, marks: 1, q: "Sivakasi is located in the state of Kerala.", ans: "False" },
    { chapter: 5, marks: 1, q: "Fireworks production in Sivakasi started before India's Independence.", ans: "False" },
    { chapter: 5, marks: 1, q: "In Sivakasi, fireworks are mainly produced for the festival of Diwali.", ans: "True" },
    { chapter: 5, marks: 1, q: "The greatest danger in the fireworks industry in Sivakasi is floods.", ans: "False" },
    { chapter: 5, marks: 1, q: "The process of making fireworks is mostly done by machines.", ans: "False" },
    { chapter: 5, marks: 1, q: "One should wear nylon clothes while lighting fireworks.", ans: "False" },
    { chapter: 5, marks: 1, q: "Fireworks should never be lit inside a house.", ans: "True" },
    { chapter: 5, marks: 1, q: "You should always bend over a firework while lighting it.", ans: "False" },
    { chapter: 5, marks: 1, q: "The Chinese are generally considered the pioneers of pyrotechnics.", ans: "True" },
    { chapter: 5, marks: 1, q: "A safety match produces heat, smoke, light, gas, and sound.", ans: "True" },
    { chapter: 5, marks: 1, q: "Incandescence is light produced by heating a substance.", ans: "True" },
    { chapter: 5, marks: 1, q: "Working with fireworks requires very low temperatures to produce colors.", ans: "False" },
    { chapter: 5, marks: 1, q: "Fireworks can be stored anywhere safely without any precautions.", ans: "False" },
    { chapter: 5, marks: 1, q: "Roger Bacon thought black powder was too dangerous to be revealed in plain text.", ans: "True" },

    // ---------------- Chapter 6: I Love You, Teacher ----------------
    { chapter: 6, marks: 1, q: "Helen Keller was born deaf and blind.", ans: "False" },
    { chapter: 6, marks: 1, q: "Helen became deaf and blind at a very young age due to an illness.", ans: "True" },
    { chapter: 6, marks: 1, q: "Helen could not learn to speak easily because she was deaf.", ans: "True" },
    { chapter: 6, marks: 1, q: "Miss Anne Sullivan was a teacher for the deaf and blind.", ans: "True" },
    { chapter: 6, marks: 1, q: "Miss Sullivan gave Helen a ball to play with on the first day.", ans: "False" },
    { chapter: 6, marks: 1, q: "Helen learned to spell words using finger movements on her palm.", ans: "True" },
    { chapter: 6, marks: 1, q: "The first word Helen successfully spelled was WATER.", ans: "False" },
    { chapter: 6, marks: 1, q: "Helen learned to speak by touching her teacher's lips and throat.", ans: "True" },
    { chapter: 6, marks: 1, q: "The word WATER awakened Helen's soul and gave her hope.", ans: "True" },
    { chapter: 6, marks: 1, q: "Helen joined the Perkins Institution in 1890.", ans: "True" },
    { chapter: 6, marks: 1, q: "Helen learned to read and write using the Braille system.", ans: "True" },
    { chapter: 6, marks: 1, q: "Helen joined the Cambridge School for Young Ladies in 1896.", ans: "True" },
    { chapter: 6, marks: 1, q: "Helen's father died after she completed her college graduation.", ans: "False" },
    { chapter: 6, marks: 1, q: "Helen graduated successfully from Radcliffe College.", ans: "True" },
    { chapter: 6, marks: 1, q: "Helen was the first deaf-blind person to earn a Bachelor of Arts degree.", ans: "True" },
    { chapter: 6, marks: 1, q: "Helen never wrote any poems or articles in her life.", ans: "False" },
    { chapter: 6, marks: 1, q: "Miss Sullivan's eyesight became weak over time.", ans: "True" },
    { chapter: 6, marks: 1, q: "Miss Sullivan stopped teaching Helen when her own eyes grew weak.", ans: "False" },
    { chapter: 6, marks: 1, q: "Miss Sullivan became completely blind in the year 1935.", ans: "True" },
    { chapter: 6, marks: 1, q: "Miss Sullivan sacrificed her eyesight for her student Helen.", ans: "True" },
    { chapter: 6, marks: 1, q: "Helen felt very happy about her teacher's blindness.", ans: "False" },
    { chapter: 6, marks: 1, q: "At the end of the lesson, Helen says, 'I hate you, teacher.'", ans: "False" },
    { chapter: 6, marks: 1, q: "Every object had a name for Helen after she learned manual spelling.", ans: "True" },
    { chapter: 6, marks: 1, q: "Helen felt connected to the world through words.", ans: "True" },
    { chapter: 6, marks: 1, q: "Helen learned to use both a Braille typewriter and a normal typewriter.", ans: "True" },
    { chapter: 6, marks: 1, q: "Miss Sullivan always stayed beside Helen to support and help her.", ans: "True" },
    { chapter: 6, marks: 1, q: "Helen learned Latin, German, and French at the Cambridge School.", ans: "True" },
    { chapter: 6, marks: 1, q: "The bond between Helen and Miss Sullivan was very weak and formal.", ans: "False" },
    { chapter: 6, marks: 1, q: "Miss Sullivan ignored her own health to continue teaching Helen.", ans: "True" },
    { chapter: 6, marks: 1, q: "Helen felt deep agony because she could not save her teacher's eyes.", ans: "True" },

    // ---------------- Chapter 7: Kach and Dev ----------------
    { chapter: 7, marks: 1, q: "The Devas and Asuras were good friends who always helped each other.", ans: "False" },
    { chapter: 7, marks: 1, q: "In the mythological stories, the Asuras were the demons.", ans: "True" },
    { chapter: 7, marks: 1, q: "Brihaspati was the chief priest and guru of the Asuras.", ans: "False" },
    { chapter: 7, marks: 1, q: "Shukracharya knew the magic formula called Sanjivani Vidya.", ans: "True" },
    { chapter: 7, marks: 1, q: "Sanjivani Vidya was used to bring the dead back to life.", ans: "True" },
    { chapter: 7, marks: 1, q: "The Devas wanted to learn the secret of Sanjivani Vidya.", ans: "True" },
    { chapter: 7, marks: 1, q: "Kach was the son of Shukracharya.", ans: "False" },
    { chapter: 7, marks: 1, q: "Kach was chosen by the Devas to learn the secret formula.", ans: "True" },
    { chapter: 7, marks: 1, q: "Kach promised to serve Shukracharya as a disciple for a thousand years.", ans: "True" },
    { chapter: 7, marks: 1, q: "Devayani was the beautiful daughter of Brihaspati.", ans: "False" },
    { chapter: 7, marks: 1, q: "Devayani fell in love with Kach.", ans: "True" },
    { chapter: 7, marks: 1, q: "Kach used to graze Shukracharya's cows in the jungle.", ans: "True" },
    { chapter: 7, marks: 1, q: "The Asuras wanted to help Kach learn the magic formula.", ans: "False" },
    { chapter: 7, marks: 1, q: "The Asuras killed Kach three times.", ans: "True" },
    { chapter: 7, marks: 1, q: "The first time, the Asuras fed Kach's body to wolves and jackals.", ans: "True" },
    { chapter: 7, marks: 1, q: "Devayani requested her father to bring Kach back to life every time.", ans: "True" },
    { chapter: 7, marks: 1, q: "The second time, the Asuras burnt Kach into ashes.", ans: "False" },
    { chapter: 7, marks: 1, q: "The third time, the Asuras mixed Kach's ashes in Shukracharya's wine.", ans: "True" },
    { chapter: 7, marks: 1, q: "Shukracharya realized through his powers that Kach was in his stomach.", ans: "True" },
    { chapter: 7, marks: 1, q: "Shukracharya taught Sanjivani Vidya to Kach while he was inside the stomach.", ans: "True" },
    { chapter: 7, marks: 1, q: "Kach came out by tearing Shukracharya's stomach.", ans: "True" },
    { chapter: 7, marks: 1, q: "Shukracharya survived when Kach tore his stomach and came out.", ans: "False" },
    { chapter: 7, marks: 1, q: "Kach used the newly learned magic formula to revive his guru.", ans: "True" },
    { chapter: 7, marks: 1, q: "Kach agreed to marry Devayani when his training was complete.", ans: "False" },
    { chapter: 7, marks: 1, q: "Kach refused to marry Devayani because he considered her his sister.", ans: "True" },
    { chapter: 7, marks: 1, q: "Devayani was very happy with Kach's decision and blessed him.", ans: "False" },
    { chapter: 7, marks: 1, q: "Devayani cursed Kach that his magic formula would not work for him.", ans: "True" },
    { chapter: 7, marks: 1, q: "Kach said he would teach the formula to someone else to pass it on.", ans: "True" },
    { chapter: 7, marks: 1, q: "Kach failed his mission to bring the Sanjivani Vidya to the Devas.", ans: "False" },
    { chapter: 7, marks: 1, q: "The Devas welcomed Kach with great joy and honor.", ans: "True" },

    // ---------------- Chapter 8: Our Feathered Friends ----------------
    { chapter: 8, marks: 1, q: "Devangi was a university student studying Botany.", ans: "False" },
    { chapter: 8, marks: 1, q: "Devangi came to visit her friend Mitra's family.", ans: "True" },
    { chapter: 8, marks: 1, q: "Subhangi was Mitra's younger sister.", ans: "True" },
    { chapter: 8, marks: 1, q: "Subhangi was very interested in knowing about birds.", ans: "True" },
    { chapter: 8, marks: 1, q: "The Tailorbird gets its name because it stitches its nest using leaves.", ans: "True" },
    { chapter: 8, marks: 1, q: "The female Tailorbird's main duty is to lay and incubate the eggs.", ans: "True" },
    { chapter: 8, marks: 1, q: "In the Weaver bird species, the female builds the nest.", ans: "False" },
    { chapter: 8, marks: 1, q: "Weaver birds prefer to build their nests on thorny trees for safety.", ans: "True" },
    { chapter: 8, marks: 1, q: "If the female Weaver bird rejects the nest, the male forces her to stay.", ans: "False" },
    { chapter: 8, marks: 1, q: "Vultures are known as the scavengers of nature.", ans: "True" },
    { chapter: 8, marks: 1, q: "Vultures keep the environment clean by eating dead animals.", ans: "True" },
    { chapter: 8, marks: 1, q: "The vulture population is rapidly increasing in India.", ans: "False" },
    { chapter: 8, marks: 1, q: "Diclofenac is a medicine that is fatal to vultures.", ans: "True" },
    { chapter: 8, marks: 1, q: "Diclofenac causes heart failure in vultures.", ans: "False" },
    { chapter: 8, marks: 1, q: "The Gujarati name for the Indian Grey Hornbill is Chilotro.", ans: "True" },
    { chapter: 8, marks: 1, q: "The Hornbill builds its nest on the ground.", ans: "False" },
    { chapter: 8, marks: 1, q: "The female Hornbill seals the nest hole using mud and her own droppings.", ans: "True" },
    { chapter: 8, marks: 1, q: "The male Hornbill feeds the female through a small slit in the sealed nest.", ans: "True" },
    { chapter: 8, marks: 1, q: "Migratory birds travel from warm regions to cold regions in winter.", ans: "False" },
    { chapter: 8, marks: 1, q: "Birds use their internal magnetic compass and the sun to navigate.", ans: "True" },
    { chapter: 8, marks: 1, q: "The state bird of Gujarat is the Greater Flamingo.", ans: "True" },
    { chapter: 8, marks: 1, q: "The local Gujarati name for the Flamingo is Surkhab.", ans: "True" },
    { chapter: 8, marks: 1, q: "Greater Flamingos are beautifully black in color.", ans: "False" },
    { chapter: 8, marks: 1, q: "Flamingos build their nests in the Rann of Kutch.", ans: "True" },
    { chapter: 8, marks: 1, q: "The nest of a Flamingo looks like a small mound made of mud.", ans: "True" },
    { chapter: 8, marks: 1, q: "Birds sing in the morning to claim their territory and attract mates.", ans: "True" },
    { chapter: 8, marks: 1, q: "Birds use their beaks only for eating food.", ans: "False" },
    { chapter: 8, marks: 1, q: "We should keep water pots and grains for birds during the hot summer.", ans: "True" },
    { chapter: 8, marks: 1, q: "Devangi advises Subhangi to catch birds and put them in cages.", ans: "False" },
    { chapter: 8, marks: 1, q: "Vultures play a crucial role in maintaining the ecological balance.", ans: "True" },

    // ---------------- Chapter 9: Tune Up, O Teens ----------------
    { chapter: 9, marks: 1, q: "The seminar 'Bring out your best' was organized by Anand Vihar School.", ans: "True" },
    { chapter: 9, marks: 1, q: "The seminar was organized for the students of class 8 and 9.", ans: "False" },
    { chapter: 9, marks: 1, q: "Mr. Saurabh Bakshi was a well-known counselor.", ans: "True" },
    { chapter: 9, marks: 1, q: "Dr. Mrs. Shalini Shah was a clinical psychologist.", ans: "True" },
    { chapter: 9, marks: 1, q: "A student named Bharat asked how to improve memory and concentration.", ans: "True" },
    { chapter: 9, marks: 1, q: "Dr. Shah suggested watching TV for better concentration.", ans: "False" },
    { chapter: 9, marks: 1, q: "Students should avoid distractions like mobile phones while studying.", ans: "True" },
    { chapter: 9, marks: 1, q: "Heavy and oily food is highly recommended during exam days.", ans: "False" },
    { chapter: 9, marks: 1, q: "Light, healthy, and easily digestible food keeps students active.", ans: "True" },
    { chapter: 9, marks: 1, q: "A student named Anuj asked a question about exam stress and blanking out.", ans: "True" },
    { chapter: 9, marks: 1, q: "Students go 'blank' during exams due to extreme fear and anxiety.", ans: "True" },
    { chapter: 9, marks: 1, q: "Exams should be treated as a matter of life and death.", ans: "False" },
    { chapter: 9, marks: 1, q: "A teenager needs at least 7 to 8 hours of sound sleep during exams.", ans: "True" },
    { chapter: 9, marks: 1, q: "Mr. Bakshi advised students to constantly compare themselves with top scorers.", ans: "False" },
    { chapter: 9, marks: 1, q: "One should only compete with oneself to improve.", ans: "True" },
    { chapter: 9, marks: 1, q: "Rucha complained that her parents expected too little from her.", ans: "False" },
    { chapter: 9, marks: 1, q: "Parents should set realistic goals based on the child's aptitude.", ans: "True" },
    { chapter: 9, marks: 1, q: "Taking short breaks during a study session is considered harmful.", ans: "False" },
    { chapter: 9, marks: 1, q: "A typical study session should be around 40 to 45 minutes before taking a break.", ans: "True" },
    { chapter: 9, marks: 1, q: "Hobbies act as stress-busters and relax the mind during exam preparation.", ans: "True" },
    { chapter: 9, marks: 1, q: "Last-minute cramming is the best way to remember everything for the exam.", ans: "False" },
    { chapter: 9, marks: 1, q: "Managing time by making a realistic timetable is very important.", ans: "True" },
    { chapter: 9, marks: 1, q: "Positive self-talk means believing in one's abilities and encouraging oneself.", ans: "True" },
    { chapter: 9, marks: 1, q: "Parents should create a very tense atmosphere on the day of the exam.", ans: "False" },
    { chapter: 9, marks: 1, q: "Drinking water keeps the brain hydrated and active during studies.", ans: "True" },
    { chapter: 9, marks: 1, q: "The principal of the school concluded the seminar and thanked the experts.", ans: "True" },
    { chapter: 9, marks: 1, q: "The seminar taught teenagers to tune up their minds positively for challenges.", ans: "True" },
    { chapter: 9, marks: 1, q: "Sleep deprivation improves memory and concentration during exams.", ans: "False" },
    { chapter: 9, marks: 1, q: "Self-awareness means the ability to understand one's own feelings.", ans: "True" },
    { chapter: 9, marks: 1, q: "The experts said that stress is a completely unnatural feeling.", ans: "False" },

      // ---------------- Chapter 10: Test of True Love ----------------
    { chapter: 10, marks: 1, q: "The main character of the story is Lieutenant John Blandford.", ans: "True" },
    { chapter: 10, marks: 1, q: "Lieutenant Blandford was waiting at Grand Central Station in London.", ans: "False" },
    { chapter: 10, marks: 1, q: "He was waiting at the station at six minutes to six.", ans: "True" },
    { chapter: 10, marks: 1, q: "Blandford was waiting to meet a woman named Hollis Meynell.", ans: "True" },
    { chapter: 10, marks: 1, q: "They had been writing letters to each other for 13 months.", ans: "True" },
    { chapter: 10, marks: 1, q: "John first learned about Hollis from a picture in a newspaper.", ans: "False" },
    { chapter: 10, marks: 1, q: "John found Hollis's notes written in a book titled 'Of Human Bondage'.", ans: "True" },
    { chapter: 10, marks: 1, q: "Hollis had sent many photographs of herself to John.", ans: "False" },
    { chapter: 10, marks: 1, q: "Hollis refused to send her picture because she believed true love doesn't depend on physical beauty.", ans: "True" },
    { chapter: 10, marks: 1, q: "They agreed to identify each other using a yellow rose.", ans: "False" },
    { chapter: 10, marks: 1, q: "John was holding the book 'Of Human Bondage' to identify himself.", ans: "True" },
    { chapter: 10, marks: 1, q: "Hollis was supposed to wear a red rose pinned to her coat.", ans: "True" },
    { chapter: 10, marks: 1, q: "As the clock struck six, John first saw a beautiful young woman in a blue suit.", ans: "False" },
    { chapter: 10, marks: 1, q: "The young woman in the green suit did not have a red rose.", ans: "True" },
    { chapter: 10, marks: 1, q: "An older woman, past forty, was walking behind the young beauty.", ans: "True" },
    { chapter: 10, marks: 1, q: "The older woman had a red rose pinned to her coat.", ans: "True" },
    { chapter: 10, marks: 1, q: "The older woman looked very beautiful, young, and slim.", ans: "False" },
    { chapter: 10, marks: 1, q: "John felt a bit disappointed when he saw the older woman with the rose.", ans: "True" },
    { chapter: 10, marks: 1, q: "John ignored the older woman and followed the young beauty.", ans: "False" },
    { chapter: 10, marks: 1, q: "John approached the older woman and greeted her respectfully.", ans: "True" },
    { chapter: 10, marks: 1, q: "John invited the older woman to join him for dinner.", ans: "True" },
    { chapter: 10, marks: 1, q: "The older woman was actually the real Hollis Meynell.", ans: "False" },
    { chapter: 10, marks: 1, q: "The young woman in the green suit had asked the older woman to wear the rose.", ans: "True" },
    { chapter: 10, marks: 1, q: "The real Hollis Meynell was waiting at the restaurant across the street.", ans: "True" },
    { chapter: 10, marks: 1, q: "Hollis Meynell arranged this situation to test John's true character.", ans: "True" },
    { chapter: 10, marks: 1, q: "John failed the test of true love.", ans: "False" },
    { chapter: 10, marks: 1, q: "The test proved that John's love was based only on physical looks.", ans: "False" },
    { chapter: 10, marks: 1, q: "John showed his loyalty and inner goodness by keeping his commitment.", ans: "True" },
    { chapter: 10, marks: 1, q: "The story highlights that true love goes beyond physical appearance and values the soul.", ans: "True" },
    { chapter: 10, marks: 1, q: "The older woman was very confused by the young lady's request but agreed to help.", ans: "True" }
    
    
];
      
