var englishTrueFalseDB_Std10 = [

    // ---------------- Chapter 1: Against the Odds ----------------
    { chapter: 1, marks: 1, q: "Taj Nagar is located near Gurgaon.", ans: "True" },
    { chapter: 1, marks: 1, q: "The villagers of Taj Nagar wanted a bus station in their village.", ans: "False" },
    { chapter: 1, marks: 1, q: "The villagers collected 21 lakh rupees to build the railway station.", ans: "True" },
    { chapter: 1, marks: 1, q: "Most of the people living in Taj Nagar are businessmen.", ans: "False" },
    { chapter: 1, marks: 1, q: "The railway department refused to build the station citing a lack of funds.", ans: "True" },
    { chapter: 1, marks: 1, q: "The villagers formed an 11-member committee to build the station.", ans: "True" },
    { chapter: 1, marks: 1, q: "The Taj Nagar railway station started operating in 2012.", ans: "False" },
    { chapter: 1, marks: 1, q: "Sitapur district is located in the state of Uttar Pradesh.", ans: "True" },
    { chapter: 1, marks: 1, q: "Over 60% of households in Sitapur were without power.", ans: "True" },
    { chapter: 1, marks: 1, q: "MGP stands for Mera Gaon Power.", ans: "True" },
    { chapter: 1, marks: 1, q: "MGP provides solar power at a higher cost than kerosene.", ans: "False" },
    { chapter: 1, marks: 1, q: "Azaz was the first electrician of the MGP project in the village.", ans: "True" },
    { chapter: 1, marks: 1, q: "Solar panels in Sitapur were installed facing North.", ans: "False" },
    { chapter: 1, marks: 1, q: "Customers in Sitapur get two LEDs and a charging point for 25 rupees a week.", ans: "True" },
    { chapter: 1, marks: 1, q: "The Palakkad Public Library is situated in Kerala.", ans: "True" },
    { chapter: 1, marks: 1, q: "The Palakkad Library was established in September 2013.", ans: "True" },
    { chapter: 1, marks: 1, q: "Only 10% of the members of the Palakkad Library are women.", ans: "False" },
    { chapter: 1, marks: 1, q: "The library launched a special women's unit in February 2014.", ans: "True" },
    { chapter: 1, marks: 1, q: "The library does not provide a separate reading room for women.", ans: "False" },
    { chapter: 1, marks: 1, q: "Workshops in the library teach women about home economics and gardening.", ans: "True" },
    { chapter: 1, marks: 1, q: "The library helps women to resolve family disputes.", ans: "True" },
    { chapter: 1, marks: 1, q: "The Palakkad Library is considered a beacon for women empowerment.", ans: "True" },
    { chapter: 1, marks: 1, q: "Taj Nagar is India's first station built completely without railway funds.", ans: "True" },
    { chapter: 1, marks: 1, q: "Micro-grids in Sitapur increased pollution in the village.", ans: "False" },
    { chapter: 1, marks: 1, q: "The women's unit in Palakkad Library encourages women to waste their time.", ans: "False" },
    { chapter: 1, marks: 1, q: "Earlier, people of Taj Nagar had to go to Halimandi or Patli to catch a train.", ans: "True" },
    { chapter: 1, marks: 1, q: "The solar panels in Sitapur are installed on weak mud walls.", ans: "False" },
    { chapter: 1, marks: 1, q: "Solar light helps weavers to work comfortably at night.", ans: "True" },
    { chapter: 1, marks: 1, q: "Women get legal advice from the Palakkad Library.", ans: "True" },
    { chapter: 1, marks: 1, q: "The villagers of Taj Nagar struggled for 25 years to get a railway station.", ans: "True" },

    // ---------------- Chapter 2: The Human Robot ----------------
    { chapter: 2, marks: 1, q: "Prem Chopra bought a robot named Ram Singh-070.", ans: "True" },
    { chapter: 2, marks: 1, q: "The robot was metallic red in color.", ans: "False" },
    { chapter: 2, marks: 1, q: "The robot was programmed to do household chores.", ans: "True" },
    { chapter: 2, marks: 1, q: "The robot operates within a radius of 10 kilometers.", ans: "False" },
    { chapter: 2, marks: 1, q: "The first principle of the robot is that it will obey its master.", ans: "True" },
    { chapter: 2, marks: 1, q: "The second principle states that the robot will harm humans.", ans: "False" },
    { chapter: 2, marks: 1, q: "The third principle is that the robot will not let harm come to itself.", ans: "True" },
    { chapter: 2, marks: 1, q: "Prem Chopra used the robot to steal precious gems.", ans: "True" },
    { chapter: 2, marks: 1, q: "Ram Singh-070 was controlled by a remote control.", ans: "True" },
    { chapter: 2, marks: 1, q: "The robot was caught stealing from Jhaveri Brothers.", ans: "True" },
    { chapter: 2, marks: 1, q: "The police used dogs to catch the robot.", ans: "False" },
    { chapter: 2, marks: 1, q: "Prem Chopra was arrested from the market.", ans: "False" },
    { chapter: 2, marks: 1, q: "Prem Chopra hired Counsel Goel as his lawyer.", ans: "True" },
    { chapter: 2, marks: 1, q: "The robot's memory tape stores information for a whole month.", ans: "False" },
    { chapter: 2, marks: 1, q: "Ram Singh-070 was called to the witness box in the court.", ans: "True" },
    { chapter: 2, marks: 1, q: "Prem Chopra threatened to defuse the robot's system.", ans: "True" },
    { chapter: 2, marks: 1, q: "The robot betrayed its master in the court.", ans: "False" },
    { chapter: 2, marks: 1, q: "The robot decided to defuse itself to save its principles.", ans: "True" },
    { chapter: 2, marks: 1, q: "Counsel Goel was happy when the robot broke into pieces.", ans: "False" },
    { chapter: 2, marks: 1, q: "The judge declared Prem Chopra innocent.", ans: "False" },
    { chapter: 2, marks: 1, q: "A license plate was hanging around the robot's neck.", ans: "True" },
    { chapter: 2, marks: 1, q: "Prem Chopra never signed any deed of sale for the robot.", ans: "False" },
    { chapter: 2, marks: 1, q: "The salesman gave Prem Chopra a warm smile.", ans: "True" },
    { chapter: 2, marks: 1, q: "Ram Singh-070 was manufactured by Super Robots Plaza.", ans: "True" },
    { chapter: 2, marks: 1, q: "The robot picked up a bunch of apples from the fruit market.", ans: "False" },
    { chapter: 2, marks: 1, q: "Prem Chopra was released on bail before the court hearing.", ans: "True" },
    { chapter: 2, marks: 1, q: "The court case against Prem Chopra was filed under the charge of theft.", ans: "True" },
    { chapter: 2, marks: 1, q: "Prem Chopra firmly believed that robots never lie.", ans: "True" },
    { chapter: 2, marks: 1, q: "The robot spoke all the secrets of its master in the court.", ans: "False" },
    { chapter: 2, marks: 1, q: "The destruction of the robot was an emotional moment in the court.", ans: "True" },

    // ---------------- Chapter 3: An Interview with Arun Krishnamurthy ----------------
    { chapter: 3, marks: 1, q: "Arun Krishnamurthy founded an NGO named EFI.", ans: "True" },
    { chapter: 3, marks: 1, q: "EFI stands for Environmentalist Foundation of India.", ans: "True" },
    { chapter: 3, marks: 1, q: "Arun started his environmental work at the age of 25.", ans: "False" },
    { chapter: 3, marks: 1, q: "The first water body Arun cleaned was a lake near his house.", ans: "True" },
    { chapter: 3, marks: 1, q: "The dirty lake near Arun's house had a lot of mosquitoes.", ans: "True" },
    { chapter: 3, marks: 1, q: "Arun's organization only works in Chennai.", ans: "False" },
    { chapter: 3, marks: 1, q: "Arun quit a high-paying job at Google to protect the environment.", ans: "True" },
    { chapter: 3, marks: 1, q: "Arun left his job at Google in the year 2010.", ans: "True" },
    { chapter: 3, marks: 1, q: "Arun calls himself an environmental activist.", ans: "False" },
    { chapter: 3, marks: 1, q: "Arun's parents did not support his environmental work.", ans: "False" },
    { chapter: 3, marks: 1, q: "Arun's teachers taught him to practice humility.", ans: "True" },
    { chapter: 3, marks: 1, q: "The EFI team uses tools like rakes and spades.", ans: "True" },
    { chapter: 3, marks: 1, q: "Arun's team cleans lakes with bare hands without any safety gear.", ans: "False" },
    { chapter: 3, marks: 1, q: "Cleaning a lake can take anywhere from 5 days to 3 months.", ans: "True" },
    { chapter: 3, marks: 1, q: "Students can join the EFI organization as volunteers.", ans: "True" },
    { chapter: 3, marks: 1, q: "Arun suggests students should dedicate 10 hours a week for the environment.", ans: "False" },
    { chapter: 3, marks: 1, q: "Arun's team dumps the garbage outside the lake in a safe place.", ans: "True" },
    { chapter: 3, marks: 1, q: "Arun creates awareness by making short films and paper bags.", ans: "True" },
    { chapter: 3, marks: 1, q: "Arun's team runs campaigns to save sea turtles.", ans: "True" },
    { chapter: 3, marks: 1, q: "Arun believes that animals teach us to be dependent on others.", ans: "False" },
    { chapter: 3, marks: 1, q: "Arun considers water to be the basis of life.", ans: "True" },
    { chapter: 3, marks: 1, q: "Throwing garbage into water bodies is good for aquatic animals.", ans: "False" },
    { chapter: 3, marks: 1, q: "EFI offers fellowships to young people interested in the environment.", ans: "True" },
    { chapter: 3, marks: 1, q: "Arun's school and college had very little green cover.", ans: "False" },
    { chapter: 3, marks: 1, q: "Arun is still in touch with his old friends from Google.", ans: "True" },
    { chapter: 3, marks: 1, q: "Arun's team makes dustbins out of collected garbage.", ans: "True" },
    { chapter: 3, marks: 1, q: "Arun advises people not to throw trash into lakes.", ans: "True" },
    { chapter: 3, marks: 1, q: "Arun mentioned that turtles and snakes were often found in the lakes.", ans: "True" },
    { chapter: 3, marks: 1, q: "Arun thinks everyone should be environmentally aware.", ans: "True" },
    { chapter: 3, marks: 1, q: "Arun and his team also clean beaches along with lakes.", ans: "True" },

    // ---------------- Chapter 4: A Wonderful Creation ----------------
    { chapter: 4, marks: 1, q: "In the story, an Angel was creating a model of a mother.", ans: "False" },
    { chapter: 4, marks: 1, q: "God had been working on the model for six consecutive days.", ans: "True" },
    { chapter: 4, marks: 1, q: "God wanted all parts of the mother to be movable and replaceable.", ans: "True" },
    { chapter: 4, marks: 1, q: "A mother's lap disappears when she stands up.", ans: "True" },
    { chapter: 4, marks: 1, q: "God decided to give the mother four pairs of hands.", ans: "False" },
    { chapter: 4, marks: 1, q: "The mother must have three pairs of eyes.", ans: "True" },
    { chapter: 4, marks: 1, q: "The first pair of eyes sees the child through closed doors.", ans: "True" },
    { chapter: 4, marks: 1, q: "The second pair of eyes is used to scold the child.", ans: "False" },
    { chapter: 4, marks: 1, q: "The third pair of eyes is meant to know all the child's secrets.", ans: "True" },
    { chapter: 4, marks: 1, q: "The Angel advised God to take rest.", ans: "True" },
    { chapter: 4, marks: 1, q: "A mother's kiss can cure a broken leg and a broken heart.", ans: "True" },
    { chapter: 4, marks: 1, q: "A mother requires very expensive food to survive.", ans: "False" },
    { chapter: 4, marks: 1, q: "When the Angel touched the model, he found it to be very hard.", ans: "False" },
    { chapter: 4, marks: 1, q: "God said that a mother is soft but also very tough.", ans: "True" },
    { chapter: 4, marks: 1, q: "A mother can think, reason, and compromise.", ans: "True" },
    { chapter: 4, marks: 1, q: "The Angel noticed a smile on the mother's cheek.", ans: "False" },
    { chapter: 4, marks: 1, q: "God said that He deliberately put the tear on the mother's cheek.", ans: "False" },
    { chapter: 4, marks: 1, q: "The tear on the cheek was considered a miracle.", ans: "True" },
    { chapter: 4, marks: 1, q: "The tear could be for joy, pain, pride, or loneliness.", ans: "True" },
    { chapter: 4, marks: 1, q: "The Angel called the creation of the mother a wonderful creation.", ans: "True" },
    { chapter: 4, marks: 1, q: "God was highly distracted while making the mother's model.", ans: "False" },
    { chapter: 4, marks: 1, q: "With six pairs of hands, a mother can manage her family without complaining.", ans: "True" },
    { chapter: 4, marks: 1, q: "When a mother is sick, she cannot heal herself.", ans: "False" },
    { chapter: 4, marks: 1, q: "The Angel thought that putting three pairs of eyes was an easy task.", ans: "False" },
    { chapter: 4, marks: 1, q: "The word 'Replaceable' means something that cannot be changed.", ans: "False" },
    { chapter: 4, marks: 1, q: "God put His best ideas into the model of the mother.", ans: "True" },
    { chapter: 4, marks: 1, q: "The story highlights a mother's immense love and sacrifice.", ans: "True" },
    { chapter: 4, marks: 1, q: "A mother can feed her family on whatever food is available.", ans: "True" },
    { chapter: 4, marks: 1, q: "God created the mother's model in just one hour.", ans: "False" },
    { chapter: 4, marks: 1, q: "The mother is considered God's best creation in the story.", ans: "True" }

];
      
